// Package compiler assembles component wirings, slot bindings, and fill
// declarations into shared generated files (cmd/main.go, go.mod).
package compiler

import (
	"bytes"
	"fmt"
	"go/format"
	"path"
	"sort"
	"strings"

	"github.com/jsell-rh/stego/internal/gen"
	"github.com/jsell-rh/stego/internal/types"
)

// AssemblerInput carries everything needed to assemble shared files.
type AssemblerInput struct {
	// ModuleName is the Go module path (e.g. "github.com/myorg/user-service").
	ModuleName string

	// ServiceName is the service name from the service declaration.
	ServiceName string

	// GoVersion is the Go version for go.mod (e.g. "1.22").
	GoVersion string

	// Port is the HTTP listen port.
	Port int

	// Wirings from component generators, in dependency order.
	Wirings []ComponentWiring

	// SlotBindings from the service declaration.
	SlotBindings []types.SlotDeclaration

	// SlotsPackage is the relative import path (under ModuleName) for the
	// generated slot operators package. If empty, slot wiring is omitted.
	SlotsPackage string
}

// ComponentWiring pairs a component name with its generator's wiring output.
type ComponentWiring struct {
	Name   string
	Wiring *gen.Wiring
}

// Assemble produces the shared generated files from component wirings and
// slot bindings. Currently produces cmd/main.go and go.mod. No files are
// ever generated under fills/ — that directory is human-owned.
func Assemble(input AssemblerInput) ([]gen.File, error) {
	if input.ModuleName == "" {
		return nil, fmt.Errorf("ModuleName must not be empty")
	}
	if input.GoVersion == "" {
		return nil, fmt.Errorf("GoVersion must not be empty")
	}
	if input.Port <= 0 {
		input.Port = 8080
	}

	mainGo, err := generateMainGo(input)
	if err != nil {
		return nil, fmt.Errorf("generating main.go: %w", err)
	}

	goMod := generateGoMod(input)

	files := []gen.File{mainGo, goMod}

	// Invariant: never generate under fills/.
	for _, f := range files {
		if strings.HasPrefix(f.Path, "fills/") {
			return nil, fmt.Errorf("assembler bug: generated file %q under fills/ directory", f.Path)
		}
	}

	return files, nil
}

func generateGoMod(input AssemblerInput) gen.File {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by stego. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "module %s\n\n", input.ModuleName)
	fmt.Fprintf(&buf, "go %s\n", input.GoVersion)

	return gen.File{
		Path:    "go.mod",
		Content: buf.Bytes(),
	}
}

func generateMainGo(input AssemblerInput) (gen.File, error) {
	var buf bytes.Buffer

	buf.WriteString("package main\n\n")

	hasRoutes := hasAnyRoutes(input)
	hasDB := needsDB(input)
	hasSlots := len(input.SlotBindings) > 0 && input.SlotsPackage != ""

	writeMainImports(&buf, input, hasRoutes, hasDB, hasSlots)

	buf.WriteString("func main() {\n")

	if hasDB {
		writeDBSetup(&buf)
	}

	writeConstructors(&buf, input)

	if hasSlots {
		writeSlotWiring(&buf, input)
	}

	if hasRoutes {
		writeRouteRegistration(&buf, input)
		writeServerStart(&buf, input)
	}

	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return gen.File{}, fmt.Errorf("formatting main.go: %w (raw:\n%s)", err, buf.String())
	}

	return gen.File{
		Path:    "cmd/main.go",
		Content: formatted,
	}, nil
}

func writeMainImports(buf *bytes.Buffer, input AssemblerInput, hasRoutes, hasDB, hasSlots bool) {
	buf.WriteString("import (\n")

	// Standard library imports.
	var stdImports []string
	if hasDB {
		stdImports = append(stdImports, `"database/sql"`)
	}
	stdImports = append(stdImports, `"fmt"`)
	stdImports = append(stdImports, `"log"`)
	if hasRoutes {
		stdImports = append(stdImports, `"net/http"`)
	}
	if hasDB {
		stdImports = append(stdImports, `"os"`)
	}
	for _, imp := range stdImports {
		fmt.Fprintf(buf, "\t%s\n", imp)
	}

	// Component imports.
	var compImports []string
	seen := make(map[string]bool)
	for _, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for _, imp := range cw.Wiring.Imports {
			fullPath := input.ModuleName + "/" + imp
			if seen[fullPath] {
				continue
			}
			seen[fullPath] = true
			alias := path.Base(imp)
			compImports = append(compImports, fmt.Sprintf("\t%s %q", alias, fullPath))
		}
	}

	// Slots package import.
	if hasSlots {
		fullPath := input.ModuleName + "/" + input.SlotsPackage
		if !seen[fullPath] {
			compImports = append(compImports, fmt.Sprintf("\tslots %q", fullPath))
		}
	}

	// Fill imports — deduplicated across all slot bindings.
	fillNames := collectFillNames(input.SlotBindings)
	for _, name := range fillNames {
		alias := fillImportAlias(name)
		fullPath := input.ModuleName + "/fills/" + name
		compImports = append(compImports, fmt.Sprintf("\t%s %q", alias, fullPath))
	}

	if len(compImports) > 0 {
		buf.WriteString("\n")
		for _, imp := range compImports {
			fmt.Fprintln(buf, imp)
		}
	}

	buf.WriteString(")\n\n")
}

func writeDBSetup(buf *bytes.Buffer) {
	buf.WriteString("\tdsn := os.Getenv(\"DATABASE_URL\")\n")
	buf.WriteString("\tif dsn == \"\" {\n")
	buf.WriteString("\t\tlog.Fatal(\"DATABASE_URL environment variable is required\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdb, err := sql.Open(\"postgres\", dsn)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\tlog.Fatal(err)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer db.Close()\n\n")
}

func writeConstructors(buf *bytes.Buffer, input AssemblerInput) {
	for _, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for _, constructor := range cw.Wiring.Constructors {
			varName := constructorVarName(constructor)
			fmt.Fprintf(buf, "\t%s := %s\n", varName, constructor)
		}
	}
	buf.WriteString("\n")
}

func writeSlotWiring(buf *bytes.Buffer, input AssemblerInput) {
	buf.WriteString("\t// Slot wiring — fills composed via operators.\n")

	for _, sb := range input.SlotBindings {
		slotPascal := snakeToPascal(sb.Slot)
		entityComment := ""
		if sb.Entity != "" {
			entityComment = fmt.Sprintf(" for %s", sb.Entity)
		}

		if len(sb.Gate) > 0 {
			varName := snakeToCamel(sb.Slot) + "Gate"
			fmt.Fprintf(buf, "\t// Slot: %s (gate)%s\n", sb.Slot, entityComment)
			fmt.Fprintf(buf, "\t%s := slots.New%sGate(\n", varName, slotPascal)
			for _, fillName := range sb.Gate {
				alias := fillImportAlias(fillName)
				fmt.Fprintf(buf, "\t\t%s.New(),\n", alias)
			}
			fmt.Fprintf(buf, "\t)\n")
			fmt.Fprintf(buf, "\t_ = %s // wired into handler via constructor injection\n\n", varName)
		}

		if len(sb.Chain) > 0 {
			varName := snakeToCamel(sb.Slot) + "Chain"
			scStr := "false"
			if sb.ShortCircuit {
				scStr = "true"
			}
			fmt.Fprintf(buf, "\t// Slot: %s (chain, short_circuit=%s)%s\n", sb.Slot, scStr, entityComment)
			fmt.Fprintf(buf, "\t%s := slots.New%sChain(%s,\n", varName, slotPascal, scStr)
			for _, fillName := range sb.Chain {
				alias := fillImportAlias(fillName)
				fmt.Fprintf(buf, "\t\t%s.New(),\n", alias)
			}
			fmt.Fprintf(buf, "\t)\n")
			fmt.Fprintf(buf, "\t_ = %s // wired into handler via constructor injection\n\n", varName)
		}

		if len(sb.FanOut) > 0 {
			varName := snakeToCamel(sb.Slot) + "FanOut"
			fmt.Fprintf(buf, "\t// Slot: %s (fan-out)%s\n", sb.Slot, entityComment)
			fmt.Fprintf(buf, "\t%s := slots.New%sFanOut(\n", varName, slotPascal)
			for _, fillName := range sb.FanOut {
				alias := fillImportAlias(fillName)
				fmt.Fprintf(buf, "\t\t%s.New(),\n", alias)
			}
			fmt.Fprintf(buf, "\t)\n")
			fmt.Fprintf(buf, "\t_ = %s // wired into handler via constructor injection\n\n", varName)
		}
	}
}

func writeRouteRegistration(buf *bytes.Buffer, input AssemblerInput) {
	buf.WriteString("\tmux := http.NewServeMux()\n")
	for _, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for _, route := range cw.Wiring.Routes {
			fmt.Fprintf(buf, "\t%s\n", route)
		}
	}
	buf.WriteString("\n")
}

func writeServerStart(buf *bytes.Buffer, input AssemblerInput) {
	// Check if there's an auth middleware to wrap the mux.
	middlewareVar := findMiddlewareVar(input)

	buf.WriteString("\taddr := fmt.Sprintf(\":%d\", ")
	fmt.Fprintf(buf, "%d)\n", input.Port)
	buf.WriteString("\tlog.Printf(\"starting server on %%s\", addr)\n")

	if middlewareVar != "" {
		fmt.Fprintf(buf, "\tlog.Fatal(http.ListenAndServe(addr, %s.Middleware(mux)))\n", middlewareVar)
	} else {
		buf.WriteString("\tlog.Fatal(http.ListenAndServe(addr, mux))\n")
	}
}

// hasAnyRoutes returns true if any component wiring has routes.
func hasAnyRoutes(input AssemblerInput) bool {
	for _, cw := range input.Wirings {
		if cw.Wiring != nil && len(cw.Wiring.Routes) > 0 {
			return true
		}
	}
	return false
}

// needsDB returns true if any constructor expression references "db" as a
// parameter, indicating database connectivity is needed.
func needsDB(input AssemblerInput) bool {
	for _, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for _, c := range cw.Wiring.Constructors {
			if strings.Contains(c, "(db)") || strings.Contains(c, "(db,") {
				return true
			}
		}
	}
	return false
}

// findMiddlewareVar returns the variable name of an auth middleware
// constructor, or "" if none exists.
func findMiddlewareVar(input AssemblerInput) string {
	for _, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for _, c := range cw.Wiring.Constructors {
			if strings.Contains(c, "AuthMiddleware") {
				return constructorVarName(c)
			}
		}
	}
	return ""
}

// constructorVarName derives a Go variable name from a constructor expression.
// "pkg.NewFooBar(args)" → "fooBar"
// "pkg.NewStore(db)" → "store"
func constructorVarName(expr string) string {
	// Extract the function name after the last dot before '('.
	funcName := expr
	if dotIdx := strings.LastIndex(expr, "."); dotIdx >= 0 {
		funcName = expr[dotIdx+1:]
	}
	if parenIdx := strings.Index(funcName, "("); parenIdx >= 0 {
		funcName = funcName[:parenIdx]
	}

	// Strip "New" prefix.
	if strings.HasPrefix(funcName, "New") {
		funcName = funcName[3:]
	}

	if len(funcName) == 0 {
		return "v"
	}

	// Lower first letter for camelCase.
	return strings.ToLower(funcName[:1]) + funcName[1:]
}

// fillImportAlias converts a fill name (e.g. "admin-creation-policy") to a
// valid Go import alias (e.g. "admincreationpolicy").
func fillImportAlias(fillName string) string {
	s := strings.ReplaceAll(fillName, "-", "")
	s = strings.ReplaceAll(s, "_", "")
	return strings.ToLower(s)
}

// collectFillNames returns a deduplicated, sorted list of fill names from
// all slot bindings.
func collectFillNames(bindings []types.SlotDeclaration) []string {
	seen := make(map[string]bool)
	var names []string
	for _, sb := range bindings {
		for _, n := range sb.Gate {
			if !seen[n] {
				seen[n] = true
				names = append(names, n)
			}
		}
		for _, n := range sb.Chain {
			if !seen[n] {
				seen[n] = true
				names = append(names, n)
			}
		}
		for _, n := range sb.FanOut {
			if !seen[n] {
				seen[n] = true
				names = append(names, n)
			}
		}
	}
	sort.Strings(names)
	return names
}

// snakeToPascal converts a snake_case string to PascalCase.
// "before_create" → "BeforeCreate"
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		result.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return result.String()
}

// snakeToCamel converts a snake_case string to camelCase.
// "before_create" → "beforeCreate"
func snakeToCamel(s string) string {
	pascal := snakeToPascal(s)
	if len(pascal) == 0 {
		return ""
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}
