// Package compiler assembles component wirings, slot bindings, and fill
// declarations into shared generated files (cmd/main.go, go.mod).
package compiler

import (
	"bytes"
	"fmt"
	"go/format"
	"path"
	"sort"
	"strings"

	"github.com/jsell-rh/stego/internal/gen"
	"github.com/jsell-rh/stego/internal/types"
)

// AssemblerInput carries everything needed to assemble shared files.
type AssemblerInput struct {
	// ModuleName is the Go module path (e.g. "github.com/myorg/user-service").
	ModuleName string

	// ServiceName is the service name from the service declaration.
	ServiceName string

	// GoVersion is the Go version for go.mod (e.g. "1.22").
	GoVersion string

	// Port is the HTTP listen port.
	Port int

	// Wirings from component generators, in dependency order.
	Wirings []ComponentWiring

	// SlotBindings from the service declaration.
	SlotBindings []types.SlotDeclaration

	// SlotsPackage is the relative import path (under ModuleName) for the
	// generated slot operators package. If empty, slot wiring is omitted.
	SlotsPackage string
}

// ComponentWiring pairs a component name with its generator's wiring output.
type ComponentWiring struct {
	Name   string
	Wiring *gen.Wiring
}

// Assemble produces the shared generated files from component wirings and
// slot bindings. Currently produces cmd/main.go and go.mod. No files are
// ever generated under fills/ — that directory is human-owned.
func Assemble(input AssemblerInput) ([]gen.File, error) {
	if input.ModuleName == "" {
		return nil, fmt.Errorf("ModuleName must not be empty")
	}
	if input.GoVersion == "" {
		return nil, fmt.Errorf("GoVersion must not be empty")
	}
	if input.Port <= 0 {
		input.Port = 8080
	}

	mainGo, err := generateMainGo(input)
	if err != nil {
		return nil, fmt.Errorf("generating main.go: %w", err)
	}

	goMod := generateGoMod(input)

	files := []gen.File{mainGo, goMod}

	// Invariant: never generate under fills/.
	for _, f := range files {
		if strings.HasPrefix(f.Path, "fills/") {
			return nil, fmt.Errorf("assembler bug: generated file %q under fills/ directory", f.Path)
		}
	}

	return files, nil
}

func generateGoMod(input AssemblerInput) gen.File {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by stego. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "module %s\n\n", input.ModuleName)
	fmt.Fprintf(&buf, "go %s\n", input.GoVersion)

	return gen.File{
		Path:    "go.mod",
		Content: buf.Bytes(),
	}
}

func generateMainGo(input AssemblerInput) (gen.File, error) {
	var buf bytes.Buffer

	buf.WriteString("package main\n\n")

	hasRoutes := hasAnyRoutes(input)
	hasDB := needsDB(input)
	hasSlots := len(input.SlotBindings) > 0 && input.SlotsPackage != ""

	// Build slot operator variable names by entity so we can inject them
	// into handler constructor calls.
	slotVarsByEntity := buildSlotVarsByEntity(input.SlotBindings, hasSlots)
	// Collect ALL slot var names (including entity-less ones) so constructor
	// disambiguation can avoid collisions with slot operators.
	allSlotVarNames := collectAllSlotVarNames(input.SlotBindings, hasSlots)

	writeMainImports(&buf, input, hasRoutes, hasDB, hasSlots)

	buf.WriteString("func main() {\n")

	if hasDB {
		writeDBSetup(&buf)
	}

	// Slot wiring — create operators before constructors so they can be
	// injected as handler constructor arguments.
	if hasSlots {
		writeSlotWiring(&buf, input, slotVarsByEntity)
	}

	wiringRenames, err := writeConstructors(&buf, input, slotVarsByEntity, allSlotVarNames, hasDB, hasRoutes)
	if err != nil {
		return gen.File{}, err
	}

	if hasRoutes {
		writeRouteRegistration(&buf, input, wiringRenames)
		writeServerStart(&buf, input, wiringRenames)
	}

	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return gen.File{}, fmt.Errorf("formatting main.go: %w (raw:\n%s)", err, buf.String())
	}

	return gen.File{
		Path:    "cmd/main.go",
		Content: formatted,
	}, nil
}

func writeMainImports(buf *bytes.Buffer, input AssemblerInput, hasRoutes, hasDB, hasSlots bool) {
	buf.WriteString("import (\n")

	// Standard library imports.
	var stdImports []string
	if hasDB {
		stdImports = append(stdImports, `"database/sql"`)
	}
	// fmt is only used in writeServerStart which is gated on hasRoutes.
	if hasRoutes {
		stdImports = append(stdImports, `"fmt"`)
	}
	// log is used in writeDBSetup and writeServerStart.
	if hasDB || hasRoutes {
		stdImports = append(stdImports, `"log"`)
	}
	if hasRoutes {
		stdImports = append(stdImports, `"net/http"`)
	}
	if hasDB {
		stdImports = append(stdImports, `"os"`)
	}
	for _, imp := range stdImports {
		fmt.Fprintf(buf, "\t%s\n", imp)
	}

	// All non-stdlib imports share a SINGLE disambiguation namespace so that
	// component, fill, and slots aliases cannot collide with each other.
	var compImports []string
	seen := make(map[string]bool)      // full import path → already added
	aliases := make(map[string]int)    // base alias → count (for disambiguation)
	aliasUsed := make(map[string]bool) // tracks the exact alias string used

	// Slots package import — registered first so its hardcoded alias "slots"
	// is reserved before any dynamic disambiguation runs.
	if hasSlots {
		fullPath := input.ModuleName + "/" + input.SlotsPackage
		if !seen[fullPath] {
			seen[fullPath] = true
			slotsAlias := disambiguateAlias("slots", aliases, aliasUsed)
			compImports = append(compImports, fmt.Sprintf("\t%s %q", slotsAlias, fullPath))
		}
	}

	// Component imports.
	for _, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for _, imp := range cw.Wiring.Imports {
			fullPath := input.ModuleName + "/" + imp
			if seen[fullPath] {
				continue
			}
			seen[fullPath] = true
			alias := disambiguateAlias(path.Base(imp), aliases, aliasUsed)
			compImports = append(compImports, fmt.Sprintf("\t%s %q", alias, fullPath))
		}
	}

	// Fill imports — deduplicated across all slot bindings.
	fillNames := collectFillNames(input.SlotBindings)
	for _, name := range fillNames {
		baseAlias := rawFillImportAlias(name)
		alias := disambiguateAlias(baseAlias, aliases, aliasUsed)
		fullPath := input.ModuleName + "/fills/" + name
		compImports = append(compImports, fmt.Sprintf("\t%s %q", alias, fullPath))
	}

	if len(compImports) > 0 {
		buf.WriteString("\n")
		for _, imp := range compImports {
			fmt.Fprintln(buf, imp)
		}
	}

	buf.WriteString(")\n\n")
}

func writeDBSetup(buf *bytes.Buffer) {
	buf.WriteString("\tdsn := os.Getenv(\"DATABASE_URL\")\n")
	buf.WriteString("\tif dsn == \"\" {\n")
	buf.WriteString("\t\tlog.Fatal(\"DATABASE_URL environment variable is required\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdb, err := sql.Open(\"postgres\", dsn)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\tlog.Fatal(err)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer db.Close()\n\n")
}

// collectAllSlotVarNames returns the set of all slot operator variable names
// that will be emitted by writeSlotWiring. This is used to seed the constructor
// variable disambiguation maps so that constructor vars cannot collide with
// slot operator vars in the same function scope.
func collectAllSlotVarNames(bindings []types.SlotDeclaration, hasSlots bool) map[string]bool {
	result := make(map[string]bool)
	if !hasSlots {
		return result
	}
	for _, sb := range bindings {
		if len(sb.Gate) > 0 {
			result[slotVarName(sb.Slot, sb.Entity, "Gate")] = true
		}
		if len(sb.Chain) > 0 {
			result[slotVarName(sb.Slot, sb.Entity, "Chain")] = true
		}
		if len(sb.FanOut) > 0 {
			result[slotVarName(sb.Slot, sb.Entity, "FanOut")] = true
		}
	}
	return result
}

// assemblerInternalVars returns the set of variable names that assembler-
// internal emitter functions (writeDBSetup, writeRouteRegistration,
// writeServerStart) introduce into the main() function scope. Constructor
// variable disambiguation must reserve these to prevent collisions.
func assemblerInternalVars(hasDB, hasRoutes bool) map[string]bool {
	vars := make(map[string]bool)
	if hasDB {
		vars["dsn"] = true
		vars["db"] = true
		vars["err"] = true
	}
	if hasRoutes {
		vars["mux"] = true
		vars["addr"] = true
	}
	return vars
}

// writeConstructors emits constructor variable declarations and returns
// per-wiring rename maps. Each entry maps a wiring index to a map from
// raw (pre-disambiguation) variable names to their disambiguated names.
// This is used by writeRouteRegistration to update variable references
// only in routes belonging to the wiring whose constructors were renamed.
func writeConstructors(buf *bytes.Buffer, input AssemblerInput, slotVarsByEntity map[string][]string, slotVarNames map[string]bool, hasDB, hasRoutes bool) (map[int]map[string]string, error) {
	varNames := make(map[string]int) // for collision detection
	varUsed := make(map[string]bool)
	wiringRenames := make(map[int]map[string]string)

	// Seed with slot operator variable names so constructor vars are
	// disambiguated against them (they share the same function scope).
	for name := range slotVarNames {
		varNames[name]++
		varUsed[name] = true
	}

	// Seed with assembler-internal template variables (mux, addr, db, dsn,
	// err) that are emitted by writeDBSetup, writeRouteRegistration, and
	// writeServerStart into the same function scope.
	for name := range assemblerInternalVars(hasDB, hasRoutes) {
		varNames[name]++
		varUsed[name] = true
	}

	for i, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for j, constructor := range cw.Wiring.Constructors {
			baseVar := rawConstructorVarName(constructor)
			varName := disambiguateAlias(baseVar, varNames, varUsed)

			if varName != baseVar {
				if wiringRenames[i] == nil {
					wiringRenames[i] = make(map[string]string)
				}
				wiringRenames[i][baseVar] = varName
			}

			// Inject slot operators into handler constructors using
			// structured metadata rather than naming convention matching.
			expr := constructor
			if entity, ok := cw.Wiring.ConstructorEntities[j]; ok && entity != "" {
				if slotVars, ok := slotVarsByEntity[entity]; ok && len(slotVars) > 0 {
					expr = injectConstructorArgs(constructor, slotVars)
				}
			}

			fmt.Fprintf(buf, "\t%s := %s\n", varName, expr)
		}
	}
	buf.WriteString("\n")
	return wiringRenames, nil
}

func writeSlotWiring(buf *bytes.Buffer, input AssemblerInput, slotVarsByEntity map[string][]string) {
	buf.WriteString("\t// Slot wiring — fills composed via operators.\n")

	// Compute fill import aliases (must match writeMainImports exactly).
	fillAliasMap := buildFillAliasMap(input)

	// Build a set of operator variable names that will be injected into
	// handler constructors. Variables NOT in this set need `_ =` to prevent
	// unused variable errors (e.g. when a slot has no entity association).
	injected := make(map[string]bool)
	for _, vars := range slotVarsByEntity {
		for _, v := range vars {
			injected[v] = true
		}
	}

	for _, sb := range input.SlotBindings {
		slotPascal := snakeToPascal(sb.Slot)
		entityComment := ""
		if sb.Entity != "" {
			entityComment = fmt.Sprintf(" for %s", sb.Entity)
		}

		if len(sb.Gate) > 0 {
			varName := slotVarName(sb.Slot, sb.Entity, "Gate")
			fmt.Fprintf(buf, "\t// Slot: %s (gate)%s\n", sb.Slot, entityComment)
			fmt.Fprintf(buf, "\t%s := slots.New%sGate(\n", varName, slotPascal)
			for _, fillName := range sb.Gate {
				alias := fillAliasMap[fillName]
				fmt.Fprintf(buf, "\t\t%s.New(),\n", alias)
			}
			fmt.Fprintf(buf, "\t)\n")
			if !injected[varName] {
				fmt.Fprintf(buf, "\t_ = %s\n", varName)
			}
			buf.WriteString("\n")
		}

		if len(sb.Chain) > 0 {
			varName := slotVarName(sb.Slot, sb.Entity, "Chain")
			scStr := "false"
			if sb.ShortCircuit {
				scStr = "true"
			}
			fmt.Fprintf(buf, "\t// Slot: %s (chain, short_circuit=%s)%s\n", sb.Slot, scStr, entityComment)
			fmt.Fprintf(buf, "\t%s := slots.New%sChain(%s,\n", varName, slotPascal, scStr)
			for _, fillName := range sb.Chain {
				alias := fillAliasMap[fillName]
				fmt.Fprintf(buf, "\t\t%s.New(),\n", alias)
			}
			fmt.Fprintf(buf, "\t)\n")
			if !injected[varName] {
				fmt.Fprintf(buf, "\t_ = %s\n", varName)
			}
			buf.WriteString("\n")
		}

		if len(sb.FanOut) > 0 {
			varName := slotVarName(sb.Slot, sb.Entity, "FanOut")
			fmt.Fprintf(buf, "\t// Slot: %s (fan-out)%s\n", sb.Slot, entityComment)
			fmt.Fprintf(buf, "\t%s := slots.New%sFanOut(\n", varName, slotPascal)
			for _, fillName := range sb.FanOut {
				alias := fillAliasMap[fillName]
				fmt.Fprintf(buf, "\t\t%s.New(),\n", alias)
			}
			fmt.Fprintf(buf, "\t)\n")
			if !injected[varName] {
				fmt.Fprintf(buf, "\t_ = %s\n", varName)
			}
			buf.WriteString("\n")
		}
	}
}

func writeRouteRegistration(buf *bytes.Buffer, input AssemblerInput, wiringRenames map[int]map[string]string) {
	buf.WriteString("\tmux := http.NewServeMux()\n")
	for i, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		renames := wiringRenames[i]
		for _, route := range cw.Wiring.Routes {
			// Update variable references that were renamed during
			// constructor disambiguation — only for this wiring's renames.
			updatedRoute := applyVarRenames(route, renames)
			fmt.Fprintf(buf, "\t%s\n", updatedRoute)
		}
	}
	buf.WriteString("\n")
}

// applyVarRenames replaces variable references in a route expression when
// constructor variable names were disambiguated. For example, if "store" was
// renamed to "store2", a route like "mux.HandleFunc(..., store.Get)" becomes
// "mux.HandleFunc(..., store2.Get)".
func applyVarRenames(route string, renames map[string]string) string {
	for oldName, newName := range renames {
		// Replace "oldName." with "newName." — the dot ensures we match
		// the variable reference (e.g. "userHandler.Create") and not a
		// substring of an unrelated identifier.
		route = strings.ReplaceAll(route, oldName+".", newName+".")
	}
	return route
}

func writeServerStart(buf *bytes.Buffer, input AssemblerInput, wiringRenames map[int]map[string]string) {
	// Check if there's an auth middleware to wrap the mux.
	middlewareVar, wiringIdx := findMiddlewareVar(input)
	// Apply disambiguation renames to the middleware variable reference.
	if renames, ok := wiringRenames[wiringIdx]; ok {
		if renamed, ok := renames[middlewareVar]; ok {
			middlewareVar = renamed
		}
	}

	buf.WriteString("\taddr := fmt.Sprintf(\":%d\", ")
	fmt.Fprintf(buf, "%d)\n", input.Port)
	buf.WriteString("\tlog.Printf(\"starting server on %%s\", addr)\n")

	if middlewareVar != "" {
		fmt.Fprintf(buf, "\tlog.Fatal(http.ListenAndServe(addr, %s.Middleware(mux)))\n", middlewareVar)
	} else {
		buf.WriteString("\tlog.Fatal(http.ListenAndServe(addr, mux))\n")
	}
}

// hasAnyRoutes returns true if any component wiring has routes.
func hasAnyRoutes(input AssemblerInput) bool {
	for _, cw := range input.Wirings {
		if cw.Wiring != nil && len(cw.Wiring.Routes) > 0 {
			return true
		}
	}
	return false
}

// needsDB returns true if any component wiring declares NeedsDB.
func needsDB(input AssemblerInput) bool {
	for _, cw := range input.Wirings {
		if cw.Wiring != nil && cw.Wiring.NeedsDB {
			return true
		}
	}
	return false
}

// findMiddlewareVar returns the variable name of an auth middleware
// constructor and the wiring index it belongs to, or ("", -1) if none exists.
// Uses structured MiddlewareConstructor metadata rather than string matching.
func findMiddlewareVar(input AssemblerInput) (string, int) {
	for i, cw := range input.Wirings {
		if cw.Wiring == nil || cw.Wiring.MiddlewareConstructor == nil {
			continue
		}
		idx := *cw.Wiring.MiddlewareConstructor
		if idx >= 0 && idx < len(cw.Wiring.Constructors) {
			return rawConstructorVarName(cw.Wiring.Constructors[idx]), i
		}
	}
	return "", -1
}

// rawConstructorVarName derives a base Go variable name from a constructor expression.
// "pkg.NewFooBar(args)" → "fooBar"
// "pkg.NewStore(db)" → "store"
func rawConstructorVarName(expr string) string {
	// Extract the function name after the last dot before '('.
	funcName := expr
	if dotIdx := strings.LastIndex(expr, "."); dotIdx >= 0 {
		funcName = expr[dotIdx+1:]
	}
	if parenIdx := strings.Index(funcName, "("); parenIdx >= 0 {
		funcName = funcName[:parenIdx]
	}

	// Strip "New" prefix.
	if strings.HasPrefix(funcName, "New") {
		funcName = funcName[3:]
	}

	if len(funcName) == 0 {
		return "v"
	}

	// Lower first letter for camelCase.
	return strings.ToLower(funcName[:1]) + funcName[1:]
}

// rawFillImportAlias converts a fill name (e.g. "admin-creation-policy") to a
// base Go import alias (e.g. "admincreationpolicy") before disambiguation.
func rawFillImportAlias(fillName string) string {
	s := strings.ReplaceAll(fillName, "-", "")
	s = strings.ReplaceAll(s, "_", "")
	return strings.ToLower(s)
}

// disambiguateAlias returns a unique alias given a base alias. If the base
// alias has been seen before, a numeric suffix is appended (e.g. "store2").
// The counts and used maps are mutated to track state across calls.
func disambiguateAlias(base string, counts map[string]int, used map[string]bool) string {
	counts[base]++
	if counts[base] == 1 {
		used[base] = true
		return base
	}
	alias := fmt.Sprintf("%s%d", base, counts[base])
	for used[alias] {
		counts[base]++
		alias = fmt.Sprintf("%s%d", base, counts[base])
	}
	used[alias] = true
	return alias
}

// injectConstructorArgs inserts additional arguments into a constructor
// expression before its closing parenthesis.
func injectConstructorArgs(expr string, args []string) string {
	if len(args) == 0 {
		return expr
	}
	closeIdx := strings.LastIndex(expr, ")")
	if closeIdx < 0 {
		return expr
	}
	openIdx := strings.Index(expr, "(")
	if openIdx < 0 {
		return expr
	}

	prefix := expr[:closeIdx]
	suffix := expr[closeIdx:]

	inner := strings.TrimSpace(expr[openIdx+1 : closeIdx])
	if inner == "" {
		return prefix + strings.Join(args, ", ") + suffix
	}
	return prefix + ", " + strings.Join(args, ", ") + suffix
}

// buildSlotVarsByEntity returns a map from entity name to a list of slot
// operator variable names for that entity. These variables are created by
// writeSlotWiring and injected into handler constructors by writeConstructors.
func buildSlotVarsByEntity(bindings []types.SlotDeclaration, hasSlots bool) map[string][]string {
	result := make(map[string][]string)
	if !hasSlots {
		return result
	}
	for _, sb := range bindings {
		if sb.Entity == "" {
			continue
		}
		if len(sb.Gate) > 0 {
			result[sb.Entity] = append(result[sb.Entity], slotVarName(sb.Slot, sb.Entity, "Gate"))
		}
		if len(sb.Chain) > 0 {
			result[sb.Entity] = append(result[sb.Entity], slotVarName(sb.Slot, sb.Entity, "Chain"))
		}
		if len(sb.FanOut) > 0 {
			result[sb.Entity] = append(result[sb.Entity], slotVarName(sb.Slot, sb.Entity, "FanOut"))
		}
	}
	return result
}

// buildFillAliasMap returns a map from fill name to its resolved import alias.
// Must replay the same unified disambiguation sequence as writeMainImports:
// slots alias first, then component import aliases, then fill aliases.
func buildFillAliasMap(input AssemblerInput) map[string]string {
	aliases := make(map[string]int)
	aliasUsed := make(map[string]bool)
	seen := make(map[string]bool)

	// Replay slots alias registration.
	hasSlots := len(input.SlotBindings) > 0 && input.SlotsPackage != ""
	if hasSlots {
		fullPath := input.ModuleName + "/" + input.SlotsPackage
		if !seen[fullPath] {
			seen[fullPath] = true
			disambiguateAlias("slots", aliases, aliasUsed)
		}
	}

	// Replay component import alias registration.
	for _, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for _, imp := range cw.Wiring.Imports {
			fullPath := input.ModuleName + "/" + imp
			if seen[fullPath] {
				continue
			}
			seen[fullPath] = true
			disambiguateAlias(path.Base(imp), aliases, aliasUsed)
		}
	}

	// Now compute fill aliases using the same namespace.
	fillNames := collectFillNames(input.SlotBindings)
	result := make(map[string]string, len(fillNames))
	for _, name := range fillNames {
		baseAlias := rawFillImportAlias(name)
		alias := disambiguateAlias(baseAlias, aliases, aliasUsed)
		result[name] = alias
	}
	return result
}

// collectFillNames returns a deduplicated, sorted list of fill names from
// all slot bindings.
func collectFillNames(bindings []types.SlotDeclaration) []string {
	seen := make(map[string]bool)
	var names []string
	for _, sb := range bindings {
		for _, n := range sb.Gate {
			if !seen[n] {
				seen[n] = true
				names = append(names, n)
			}
		}
		for _, n := range sb.Chain {
			if !seen[n] {
				seen[n] = true
				names = append(names, n)
			}
		}
		for _, n := range sb.FanOut {
			if !seen[n] {
				seen[n] = true
				names = append(names, n)
			}
		}
	}
	sort.Strings(names)
	return names
}

// snakeToPascal converts a snake_case string to PascalCase.
// "before_create" → "BeforeCreate"
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		result.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return result.String()
}

// snakeToCamel converts a snake_case string to camelCase.
// "before_create" → "beforeCreate"
func snakeToCamel(s string) string {
	pascal := snakeToPascal(s)
	if len(pascal) == 0 {
		return ""
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}

// slotVarName derives a unique slot operator variable name from the slot name,
// entity name (may be empty), and operator type suffix ("Gate", "Chain", "FanOut").
// When an entity is set, the entity name is included to disambiguate per-entity
// bindings of the same slot (e.g. "beforeCreateUserGate" vs "beforeCreateOrgGate").
func slotVarName(slot, entity, operatorSuffix string) string {
	base := snakeToCamel(slot)
	if entity != "" {
		base += entity
	}
	return base + operatorSuffix
}
