// Package compiler assembles component wirings, slot bindings, and fill
// declarations into shared generated files (cmd/main.go, go.mod).
package compiler

import (
	"bytes"
	"fmt"
	"go/format"
	"path"
	"sort"
	"strings"

	"github.com/jsell-rh/stego/internal/gen"
	"github.com/jsell-rh/stego/internal/types"
)

// AssemblerInput carries everything needed to assemble shared files.
type AssemblerInput struct {
	// ModuleName is the Go module path (e.g. "github.com/myorg/user-service").
	ModuleName string

	// ServiceName is the service name from the service declaration.
	ServiceName string

	// GoVersion is the Go version for go.mod (e.g. "1.22").
	GoVersion string

	// Port is the HTTP listen port.
	Port int

	// Wirings from component generators, in dependency order.
	Wirings []ComponentWiring

	// SlotBindings from the service declaration.
	SlotBindings []types.SlotDeclaration

	// SlotsPackage is the relative import path (under ModuleName) for the
	// generated slot operators package. If empty, slot wiring is omitted.
	SlotsPackage string
}

// ComponentWiring pairs a component name with its generator's wiring output.
type ComponentWiring struct {
	Name   string
	Wiring *gen.Wiring
}

// Assemble produces the shared generated files from component wirings and
// slot bindings. Currently produces cmd/main.go and go.mod. No files are
// ever generated under fills/ — that directory is human-owned.
func Assemble(input AssemblerInput) ([]gen.File, error) {
	if input.ModuleName == "" {
		return nil, fmt.Errorf("ModuleName must not be empty")
	}
	if input.GoVersion == "" {
		return nil, fmt.Errorf("GoVersion must not be empty")
	}
	if input.Port <= 0 {
		input.Port = 8080
	}

	mainGo, err := generateMainGo(input)
	if err != nil {
		return nil, fmt.Errorf("generating main.go: %w", err)
	}

	goMod := generateGoMod(input)

	files := []gen.File{mainGo, goMod}

	// Invariant: never generate under fills/.
	for _, f := range files {
		if strings.HasPrefix(f.Path, "fills/") {
			return nil, fmt.Errorf("assembler bug: generated file %q under fills/ directory", f.Path)
		}
	}

	return files, nil
}

func generateGoMod(input AssemblerInput) gen.File {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by stego. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "module %s\n\n", input.ModuleName)
	fmt.Fprintf(&buf, "go %s\n", input.GoVersion)

	return gen.File{
		Path:    "go.mod",
		Content: buf.Bytes(),
	}
}

func generateMainGo(input AssemblerInput) (gen.File, error) {
	var buf bytes.Buffer

	buf.WriteString("package main\n\n")

	hasRoutes := hasAnyRoutes(input)
	hasDB := needsDB(input)
	hasSlots := len(input.SlotBindings) > 0 && input.SlotsPackage != ""

	// Validate no duplicate (slot, entity, operator) triples before processing.
	if err := validateSlotBindingUniqueness(input.SlotBindings); err != nil {
		return gen.File{}, err
	}

	// Validate no derived variable name collisions (distinct raw composite
	// keys that normalize to the same camelCase identifier, e.g.
	// "before_create" and "before__create" both produce "beforeCreate").
	if err := validateSlotVarNameUniqueness(input.SlotBindings); err != nil {
		return gen.File{}, err
	}

	// Validate no intra-wiring constructor base name collisions.
	if err := validateConstructorUniqueness(input.Wirings); err != nil {
		return gen.File{}, err
	}

	// Build slot operator variable names by entity so we can inject them
	// into handler constructor calls.
	slotVarsByEntity := buildSlotVarsByEntity(input.SlotBindings, hasSlots)
	// Collect ALL slot var names (including entity-less ones) so constructor
	// disambiguation can avoid collisions with slot operators.
	allSlotVarNames := collectAllSlotVarNames(input.SlotBindings, hasSlots)

	importRenames := writeMainImports(&buf, input, hasRoutes, hasDB, hasSlots)

	buf.WriteString("func main() {\n")

	if hasDB {
		writeDBSetup(&buf)
	}

	// Slot wiring — create operators before constructors so they can be
	// injected as handler constructor arguments.
	if hasSlots {
		writeSlotWiring(&buf, input, slotVarsByEntity)
	}

	wiringRenames, err := writeConstructors(&buf, input, slotVarsByEntity, allSlotVarNames, hasDB, hasRoutes, importRenames)
	if err != nil {
		return gen.File{}, err
	}

	if hasRoutes {
		writeRouteRegistration(&buf, input, wiringRenames, importRenames)
		writeServerStart(&buf, input, wiringRenames)
	}

	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return gen.File{}, fmt.Errorf("formatting main.go: %w (raw:\n%s)", err, buf.String())
	}

	return gen.File{
		Path:    "cmd/main.go",
		Content: formatted,
	}, nil
}

// writeMainImports writes the import block and returns per-wiring import alias
// renames. Each entry maps a wiring index to a map from the original package
// base name to the disambiguated alias (only where they differ). This allows
// constructor and route expressions to be updated when their component's import
// alias is disambiguated.
func writeMainImports(buf *bytes.Buffer, input AssemblerInput, hasRoutes, hasDB, hasSlots bool) map[int]map[string]string {
	buf.WriteString("import (\n")

	// Standard library imports.
	var stdImports []string
	if hasDB {
		stdImports = append(stdImports, `"database/sql"`)
	}
	// fmt is only used in writeServerStart which is gated on hasRoutes.
	if hasRoutes {
		stdImports = append(stdImports, `"fmt"`)
	}
	// log is used in writeDBSetup and writeServerStart.
	if hasDB || hasRoutes {
		stdImports = append(stdImports, `"log"`)
	}
	if hasRoutes {
		stdImports = append(stdImports, `"net/http"`)
	}
	if hasDB {
		stdImports = append(stdImports, `"os"`)
	}
	for _, imp := range stdImports {
		fmt.Fprintf(buf, "\t%s\n", imp)
	}

	// All non-stdlib imports share a SINGLE disambiguation namespace so that
	// component, fill, and slots aliases cannot collide with each other.
	var compImports []string
	seen := make(map[string]bool)      // full import path → already added
	aliases := make(map[string]int)    // base alias → count (for disambiguation)
	aliasUsed := make(map[string]bool) // tracks the exact alias string used

	// Seed the disambiguation maps with stdlib import aliases so that
	// non-stdlib imports cannot shadow them. A component import like
	// "internal/sql" would otherwise get alias "sql", shadowing the
	// stdlib "database/sql" import.
	for _, name := range stdlibAliases(hasRoutes, hasDB) {
		aliases[name]++
		aliasUsed[name] = true
	}

	// Track per-wiring import alias renames for propagation to constructor
	// and route expressions.
	importRenames := make(map[int]map[string]string)

	// Slots package import — registered first so its hardcoded alias "slots"
	// is reserved before any dynamic disambiguation runs.
	if hasSlots {
		fullPath := input.ModuleName + "/" + input.SlotsPackage
		if !seen[fullPath] {
			seen[fullPath] = true
			slotsAlias := disambiguateAlias("slots", aliases, aliasUsed)
			compImports = append(compImports, fmt.Sprintf("\t%s %q", slotsAlias, fullPath))
		}
	}

	// Component imports.
	for i, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for _, imp := range cw.Wiring.Imports {
			fullPath := input.ModuleName + "/" + imp
			if seen[fullPath] {
				continue
			}
			seen[fullPath] = true
			base := path.Base(imp)
			alias := disambiguateAlias(base, aliases, aliasUsed)
			compImports = append(compImports, fmt.Sprintf("\t%s %q", alias, fullPath))
			if alias != base {
				if importRenames[i] == nil {
					importRenames[i] = make(map[string]string)
				}
				importRenames[i][base] = alias
			}
		}
	}

	// Fill imports — deduplicated across all slot bindings.
	fillNames := collectFillNames(input.SlotBindings)
	for _, name := range fillNames {
		baseAlias := rawFillImportAlias(name)
		alias := disambiguateAlias(baseAlias, aliases, aliasUsed)
		fullPath := input.ModuleName + "/fills/" + name
		compImports = append(compImports, fmt.Sprintf("\t%s %q", alias, fullPath))
	}

	if len(compImports) > 0 {
		buf.WriteString("\n")
		for _, imp := range compImports {
			fmt.Fprintln(buf, imp)
		}
	}

	buf.WriteString(")\n\n")

	return importRenames
}

func writeDBSetup(buf *bytes.Buffer) {
	buf.WriteString("\tdsn := os.Getenv(\"DATABASE_URL\")\n")
	buf.WriteString("\tif dsn == \"\" {\n")
	buf.WriteString("\t\tlog.Fatal(\"DATABASE_URL environment variable is required\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdb, err := sql.Open(\"postgres\", dsn)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\tlog.Fatal(err)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer db.Close()\n\n")
}

// collectAllSlotVarNames returns the set of all slot operator variable names
// that will be emitted by writeSlotWiring. This is used to seed the constructor
// variable disambiguation maps so that constructor vars cannot collide with
// slot operator vars in the same function scope.
func collectAllSlotVarNames(bindings []types.SlotDeclaration, hasSlots bool) map[string]bool {
	result := make(map[string]bool)
	if !hasSlots {
		return result
	}
	for _, sb := range bindings {
		if len(sb.Gate) > 0 {
			result[slotVarName(sb.Slot, sb.Entity, "Gate")] = true
		}
		if len(sb.Chain) > 0 {
			result[slotVarName(sb.Slot, sb.Entity, "Chain")] = true
		}
		if len(sb.FanOut) > 0 {
			result[slotVarName(sb.Slot, sb.Entity, "FanOut")] = true
		}
	}
	return result
}

// assemblerInternalVars returns the set of variable names that assembler-
// internal emitter functions (writeDBSetup, writeRouteRegistration,
// writeServerStart) introduce into the main() function scope, PLUS standard
// library import aliases that are used after constructor declarations (and
// would be shadowed by a local variable of the same name). Constructor
// variable disambiguation must reserve all of these to prevent collisions.
func assemblerInternalVars(hasDB, hasRoutes bool) map[string]bool {
	vars := make(map[string]bool)
	if hasDB {
		vars["dsn"] = true
		vars["db"] = true
		vars["err"] = true
		// stdlib import aliases used in writeDBSetup (before constructors,
		// but reserve defensively to prevent shadowing for any future post-
		// constructor usage).
		vars["sql"] = true
		vars["os"] = true
	}
	if hasRoutes {
		vars["mux"] = true
		vars["addr"] = true
		// stdlib import aliases used in writeRouteRegistration and
		// writeServerStart, which run AFTER constructors. A constructor
		// variable with the same name (e.g. logger.NewLog() → "log")
		// would shadow the import, breaking post-constructor references.
		vars["fmt"] = true
		vars["http"] = true
	}
	if hasDB || hasRoutes {
		// "log" is used in writeServerStart (after constructors) when
		// hasRoutes, and in writeDBSetup (before constructors) when hasDB.
		// Reserve whenever it is imported.
		vars["log"] = true
	}
	return vars
}

// constructorRename tracks a single constructor variable's original and
// disambiguated names, along with the constructor index within its wiring.
type constructorRename struct {
	ConstructorIndex int
	OriginalVar      string
	FinalVar         string
}

// writeConstructors emits constructor variable declarations and returns
// per-wiring rename lists. Each entry maps a wiring index to the list of
// constructors that were renamed (original → final variable name), keyed by
// constructor index within the wiring. Using a per-constructor-index structure
// (instead of map[string]string keyed by base name) avoids overwrite when two
// constructors in the same wiring derive the same base variable name.
// importRenames carries per-wiring import alias renames from writeMainImports;
// constructor expressions are updated to reference the disambiguated aliases.
func writeConstructors(buf *bytes.Buffer, input AssemblerInput, slotVarsByEntity map[string][]string, slotVarNames map[string]bool, hasDB, hasRoutes bool, importRenames map[int]map[string]string) (map[int][]constructorRename, error) {
	varNames := make(map[string]int) // for collision detection
	varUsed := make(map[string]bool)
	wiringRenames := make(map[int][]constructorRename)

	// Seed with slot operator variable names so constructor vars are
	// disambiguated against them (they share the same function scope).
	for name := range slotVarNames {
		varNames[name]++
		varUsed[name] = true
	}

	// Seed with assembler-internal template variables (mux, addr, db, dsn,
	// err) and standard library import aliases (log, fmt, http, os, sql)
	// that are emitted by writeDBSetup, writeRouteRegistration, and
	// writeServerStart into the same function scope.
	for name := range assemblerInternalVars(hasDB, hasRoutes) {
		varNames[name]++
		varUsed[name] = true
	}

	for i, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for j, constructor := range cw.Wiring.Constructors {
			// Apply import alias renames to the constructor expression so
			// that package-qualified references match the disambiguated
			// import aliases (e.g. "models.NewBar()" → "models2.NewBar()").
			resolvedExpr := constructor
			if renames, ok := importRenames[i]; ok {
				for oldBase, newAlias := range renames {
					resolvedExpr = replaceIdentRef(resolvedExpr, oldBase, newAlias)
				}
			}

			baseVar := rawConstructorVarName(constructor)
			varName := disambiguateAlias(baseVar, varNames, varUsed)

			if varName != baseVar {
				wiringRenames[i] = append(wiringRenames[i], constructorRename{
					ConstructorIndex: j,
					OriginalVar:      baseVar,
					FinalVar:         varName,
				})
			}

			// Inject slot operators into handler constructors using
			// structured metadata rather than naming convention matching.
			expr := resolvedExpr
			if entity, ok := cw.Wiring.ConstructorEntities[j]; ok && entity != "" {
				if slotVars, ok := slotVarsByEntity[entity]; ok && len(slotVars) > 0 {
					expr = injectConstructorArgs(resolvedExpr, slotVars)
				}
			}

			fmt.Fprintf(buf, "\t%s := %s\n", varName, expr)
		}
	}
	buf.WriteString("\n")
	return wiringRenames, nil
}

func writeSlotWiring(buf *bytes.Buffer, input AssemblerInput, slotVarsByEntity map[string][]string) {
	buf.WriteString("\t// Slot wiring — fills composed via operators.\n")

	// Compute fill import aliases (must match writeMainImports exactly).
	fillAliasMap := buildFillAliasMap(input)

	// Build a set of operator variable names that will be injected into
	// handler constructors. Variables NOT in this set need `_ =` to prevent
	// unused variable errors (e.g. when a slot has no entity association).
	injected := make(map[string]bool)
	for _, vars := range slotVarsByEntity {
		for _, v := range vars {
			injected[v] = true
		}
	}

	for _, sb := range input.SlotBindings {
		slotPascal := snakeToPascal(sb.Slot)
		entityComment := ""
		if sb.Entity != "" {
			entityComment = fmt.Sprintf(" for %s", sb.Entity)
		}

		if len(sb.Gate) > 0 {
			varName := slotVarName(sb.Slot, sb.Entity, "Gate")
			fmt.Fprintf(buf, "\t// Slot: %s (gate)%s\n", sb.Slot, entityComment)
			fmt.Fprintf(buf, "\t%s := slots.New%sGate(\n", varName, slotPascal)
			for _, fillName := range sb.Gate {
				alias := fillAliasMap[fillName]
				fmt.Fprintf(buf, "\t\t%s.New(),\n", alias)
			}
			fmt.Fprintf(buf, "\t)\n")
			if !injected[varName] {
				fmt.Fprintf(buf, "\t_ = %s\n", varName)
			}
			buf.WriteString("\n")
		}

		if len(sb.Chain) > 0 {
			varName := slotVarName(sb.Slot, sb.Entity, "Chain")
			scStr := "false"
			if sb.ShortCircuit {
				scStr = "true"
			}
			fmt.Fprintf(buf, "\t// Slot: %s (chain, short_circuit=%s)%s\n", sb.Slot, scStr, entityComment)
			fmt.Fprintf(buf, "\t%s := slots.New%sChain(%s,\n", varName, slotPascal, scStr)
			for _, fillName := range sb.Chain {
				alias := fillAliasMap[fillName]
				fmt.Fprintf(buf, "\t\t%s.New(),\n", alias)
			}
			fmt.Fprintf(buf, "\t)\n")
			if !injected[varName] {
				fmt.Fprintf(buf, "\t_ = %s\n", varName)
			}
			buf.WriteString("\n")
		}

		if len(sb.FanOut) > 0 {
			varName := slotVarName(sb.Slot, sb.Entity, "FanOut")
			fmt.Fprintf(buf, "\t// Slot: %s (fan-out)%s\n", sb.Slot, entityComment)
			fmt.Fprintf(buf, "\t%s := slots.New%sFanOut(\n", varName, slotPascal)
			for _, fillName := range sb.FanOut {
				alias := fillAliasMap[fillName]
				fmt.Fprintf(buf, "\t\t%s.New(),\n", alias)
			}
			fmt.Fprintf(buf, "\t)\n")
			if !injected[varName] {
				fmt.Fprintf(buf, "\t_ = %s\n", varName)
			}
			buf.WriteString("\n")
		}
	}
}

func writeRouteRegistration(buf *bytes.Buffer, input AssemblerInput, wiringRenames map[int][]constructorRename, importRenames map[int]map[string]string) {
	buf.WriteString("\tmux := http.NewServeMux()\n")
	for i, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for _, route := range cw.Wiring.Routes {
			// Apply import alias renames so package-qualified references
			// in route expressions match the disambiguated import aliases.
			updatedRoute := route
			if irenames, ok := importRenames[i]; ok {
				for oldBase, newAlias := range irenames {
					updatedRoute = replaceIdentRef(updatedRoute, oldBase, newAlias)
				}
			}
			// Update variable references that were renamed during
			// constructor disambiguation — only for this wiring's renames.
			// Each rename is applied independently and only matches at
			// identifier word boundaries, preventing cross-constructor
			// misdirection (see finding 17).
			updatedRoute = applyConstructorRenames(updatedRoute, wiringRenames[i])
			fmt.Fprintf(buf, "\t%s\n", updatedRoute)
		}
	}
	buf.WriteString("\n")
}

// applyConstructorRenames replaces variable references in a route expression
// when constructor variable names were disambiguated. Each rename is applied
// independently using word-boundary-safe replacement.
func applyConstructorRenames(route string, renames []constructorRename) string {
	for _, r := range renames {
		route = replaceIdentRef(route, r.OriginalVar, r.FinalVar)
	}
	return route
}

// replaceIdentRef replaces occurrences of oldName followed by a dot with
// newName followed by a dot, but only at identifier word boundaries. This
// prevents "store." from matching within "datastore.".
func replaceIdentRef(s, oldName, newName string) string {
	if oldName == newName {
		return s
	}
	target := oldName + "."
	var result strings.Builder
	i := 0
	for i < len(s) {
		idx := strings.Index(s[i:], target)
		if idx < 0 {
			result.WriteString(s[i:])
			break
		}
		absIdx := i + idx
		// Check word boundary: character before match must not be an identifier char.
		if absIdx > 0 && isIdentChar(s[absIdx-1]) {
			// Not at a word boundary — copy through this non-match and continue.
			result.WriteString(s[i : absIdx+len(target)])
			i = absIdx + len(target)
			continue
		}
		// Word boundary match — replace.
		result.WriteString(s[i:absIdx])
		result.WriteString(newName + ".")
		i = absIdx + len(target)
	}
	return result.String()
}

// isIdentChar returns true if b is a valid Go identifier character.
func isIdentChar(b byte) bool {
	return (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || (b >= '0' && b <= '9') || b == '_'
}

func writeServerStart(buf *bytes.Buffer, input AssemblerInput, wiringRenames map[int][]constructorRename) {
	// Check if there's an auth middleware to wrap the mux.
	middlewareVar, wiringIdx, constructorIdx := findMiddlewareVar(input)
	// Apply disambiguation renames to the middleware variable reference,
	// matching by constructor index to avoid misdirection when multiple
	// constructors in the same wiring share the same base variable name.
	for _, r := range wiringRenames[wiringIdx] {
		if r.ConstructorIndex == constructorIdx {
			middlewareVar = r.FinalVar
			break
		}
	}

	buf.WriteString("\taddr := fmt.Sprintf(\":%d\", ")
	fmt.Fprintf(buf, "%d)\n", input.Port)
	buf.WriteString("\tlog.Printf(\"starting server on %%s\", addr)\n")

	if middlewareVar != "" {
		fmt.Fprintf(buf, "\tlog.Fatal(http.ListenAndServe(addr, %s.Middleware(mux)))\n", middlewareVar)
	} else {
		buf.WriteString("\tlog.Fatal(http.ListenAndServe(addr, mux))\n")
	}
}

// hasAnyRoutes returns true if any component wiring has routes.
func hasAnyRoutes(input AssemblerInput) bool {
	for _, cw := range input.Wirings {
		if cw.Wiring != nil && len(cw.Wiring.Routes) > 0 {
			return true
		}
	}
	return false
}

// needsDB returns true if any component wiring declares NeedsDB.
func needsDB(input AssemblerInput) bool {
	for _, cw := range input.Wirings {
		if cw.Wiring != nil && cw.Wiring.NeedsDB {
			return true
		}
	}
	return false
}

// findMiddlewareVar returns the variable name of an auth middleware
// constructor, the wiring index it belongs to, and the constructor index
// within that wiring. Returns ("", -1, -1) if none exists.
// Uses structured MiddlewareConstructor metadata rather than string matching.
func findMiddlewareVar(input AssemblerInput) (string, int, int) {
	for i, cw := range input.Wirings {
		if cw.Wiring == nil || cw.Wiring.MiddlewareConstructor == nil {
			continue
		}
		idx := *cw.Wiring.MiddlewareConstructor
		if idx >= 0 && idx < len(cw.Wiring.Constructors) {
			return rawConstructorVarName(cw.Wiring.Constructors[idx]), i, idx
		}
	}
	return "", -1, -1
}

// rawConstructorVarName derives a base Go variable name from a constructor expression.
// "pkg.NewFooBar(args)" → "fooBar"
// "pkg.NewStore(db)" → "store"
func rawConstructorVarName(expr string) string {
	// Extract the function name after the last dot before '('.
	funcName := expr
	if dotIdx := strings.LastIndex(expr, "."); dotIdx >= 0 {
		funcName = expr[dotIdx+1:]
	}
	if parenIdx := strings.Index(funcName, "("); parenIdx >= 0 {
		funcName = funcName[:parenIdx]
	}

	// Strip "New" prefix.
	if strings.HasPrefix(funcName, "New") {
		funcName = funcName[3:]
	}

	if len(funcName) == 0 {
		return "v"
	}

	// Lower first letter for camelCase.
	return strings.ToLower(funcName[:1]) + funcName[1:]
}

// rawFillImportAlias converts a fill name (e.g. "admin-creation-policy") to a
// base Go import alias (e.g. "admincreationpolicy") before disambiguation.
func rawFillImportAlias(fillName string) string {
	s := strings.ReplaceAll(fillName, "-", "")
	s = strings.ReplaceAll(s, "_", "")
	return strings.ToLower(s)
}

// disambiguateAlias returns a unique alias given a base alias. If the base
// alias has been seen before, a numeric suffix is appended (e.g. "store2").
// The counts and used maps are mutated to track state across calls.
func disambiguateAlias(base string, counts map[string]int, used map[string]bool) string {
	counts[base]++
	if counts[base] == 1 {
		used[base] = true
		return base
	}
	alias := fmt.Sprintf("%s%d", base, counts[base])
	for used[alias] {
		counts[base]++
		alias = fmt.Sprintf("%s%d", base, counts[base])
	}
	used[alias] = true
	return alias
}

// injectConstructorArgs inserts additional arguments into a constructor
// expression before its closing parenthesis.
func injectConstructorArgs(expr string, args []string) string {
	if len(args) == 0 {
		return expr
	}
	closeIdx := strings.LastIndex(expr, ")")
	if closeIdx < 0 {
		return expr
	}
	openIdx := strings.Index(expr, "(")
	if openIdx < 0 {
		return expr
	}

	prefix := expr[:closeIdx]
	suffix := expr[closeIdx:]

	inner := strings.TrimSpace(expr[openIdx+1 : closeIdx])
	if inner == "" {
		return prefix + strings.Join(args, ", ") + suffix
	}
	return prefix + ", " + strings.Join(args, ", ") + suffix
}

// buildSlotVarsByEntity returns a map from entity name to a list of slot
// operator variable names for that entity. These variables are created by
// writeSlotWiring and injected into handler constructors by writeConstructors.
func buildSlotVarsByEntity(bindings []types.SlotDeclaration, hasSlots bool) map[string][]string {
	result := make(map[string][]string)
	if !hasSlots {
		return result
	}
	for _, sb := range bindings {
		if sb.Entity == "" {
			continue
		}
		if len(sb.Gate) > 0 {
			result[sb.Entity] = append(result[sb.Entity], slotVarName(sb.Slot, sb.Entity, "Gate"))
		}
		if len(sb.Chain) > 0 {
			result[sb.Entity] = append(result[sb.Entity], slotVarName(sb.Slot, sb.Entity, "Chain"))
		}
		if len(sb.FanOut) > 0 {
			result[sb.Entity] = append(result[sb.Entity], slotVarName(sb.Slot, sb.Entity, "FanOut"))
		}
	}
	return result
}

// buildFillAliasMap returns a map from fill name to its resolved import alias.
// Must replay the same unified disambiguation sequence as writeMainImports:
// slots alias first, then component import aliases, then fill aliases.
func buildFillAliasMap(input AssemblerInput) map[string]string {
	aliases := make(map[string]int)
	aliasUsed := make(map[string]bool)
	seen := make(map[string]bool)

	// Seed stdlib aliases (must match writeMainImports exactly).
	hasRoutes := hasAnyRoutes(input)
	hasDB := needsDB(input)
	for _, name := range stdlibAliases(hasRoutes, hasDB) {
		aliases[name]++
		aliasUsed[name] = true
	}

	// Replay slots alias registration.
	hasSlots := len(input.SlotBindings) > 0 && input.SlotsPackage != ""
	if hasSlots {
		fullPath := input.ModuleName + "/" + input.SlotsPackage
		if !seen[fullPath] {
			seen[fullPath] = true
			disambiguateAlias("slots", aliases, aliasUsed)
		}
	}

	// Replay component import alias registration.
	for _, cw := range input.Wirings {
		if cw.Wiring == nil {
			continue
		}
		for _, imp := range cw.Wiring.Imports {
			fullPath := input.ModuleName + "/" + imp
			if seen[fullPath] {
				continue
			}
			seen[fullPath] = true
			disambiguateAlias(path.Base(imp), aliases, aliasUsed)
		}
	}

	// Now compute fill aliases using the same namespace.
	fillNames := collectFillNames(input.SlotBindings)
	result := make(map[string]string, len(fillNames))
	for _, name := range fillNames {
		baseAlias := rawFillImportAlias(name)
		alias := disambiguateAlias(baseAlias, aliases, aliasUsed)
		result[name] = alias
	}
	return result
}

// collectFillNames returns a deduplicated, sorted list of fill names from
// all slot bindings.
func collectFillNames(bindings []types.SlotDeclaration) []string {
	seen := make(map[string]bool)
	var names []string
	for _, sb := range bindings {
		for _, n := range sb.Gate {
			if !seen[n] {
				seen[n] = true
				names = append(names, n)
			}
		}
		for _, n := range sb.Chain {
			if !seen[n] {
				seen[n] = true
				names = append(names, n)
			}
		}
		for _, n := range sb.FanOut {
			if !seen[n] {
				seen[n] = true
				names = append(names, n)
			}
		}
	}
	sort.Strings(names)
	return names
}

// snakeToPascal converts a snake_case string to PascalCase.
// "before_create" → "BeforeCreate"
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		result.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return result.String()
}

// snakeToCamel converts a snake_case string to camelCase.
// "before_create" → "beforeCreate"
func snakeToCamel(s string) string {
	pascal := snakeToPascal(s)
	if len(pascal) == 0 {
		return ""
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}

// validateConstructorUniqueness checks that within each wiring, no two
// constructors derive the same base variable name. Intra-wiring name
// collisions make route-to-constructor binding ambiguous — the assembler
// cannot determine which constructor a route expression references when
// multiple constructors share the same derived variable name.
func validateConstructorUniqueness(wirings []ComponentWiring) error {
	for _, cw := range wirings {
		if cw.Wiring == nil {
			continue
		}
		seen := make(map[string]string) // base var name → first constructor expression
		for _, constructor := range cw.Wiring.Constructors {
			baseVar := rawConstructorVarName(constructor)
			if first, ok := seen[baseVar]; ok {
				return fmt.Errorf("component %q has multiple constructors deriving variable name %q: %q and %q — constructor names within a component must be distinct",
					cw.Name, baseVar, first, constructor)
			}
			seen[baseVar] = constructor
		}
	}
	return nil
}

// validateSlotBindingUniqueness checks that no two slot bindings share the same
// (slot, entity, operator) composite key. Duplicate bindings would produce
// duplicate variable declarations in the generated main.go.
func validateSlotBindingUniqueness(bindings []types.SlotDeclaration) error {
	type compositeKey struct {
		slot, entity, operator string
	}
	seen := make(map[compositeKey]bool)

	for _, sb := range bindings {
		operators := []struct {
			name string
			has  bool
		}{
			{"gate", len(sb.Gate) > 0},
			{"chain", len(sb.Chain) > 0},
			{"fan-out", len(sb.FanOut) > 0},
		}
		for _, op := range operators {
			if !op.has {
				continue
			}
			key := compositeKey{slot: sb.Slot, entity: sb.Entity, operator: op.name}
			if seen[key] {
				entityDesc := ""
				if sb.Entity != "" {
					entityDesc = fmt.Sprintf(" for entity %q", sb.Entity)
				}
				return fmt.Errorf("duplicate slot binding: slot %q%s with operator %q appears more than once", sb.Slot, entityDesc, op.name)
			}
			seen[key] = true
		}
	}
	return nil
}

// stdlibAliases returns the set of implicit package-name aliases introduced by
// conditionally-imported standard library packages. These must be seeded into
// import alias disambiguation maps to prevent non-stdlib imports from shadowing
// them (e.g. component "internal/sql" getting alias "sql" and shadowing
// "database/sql").
func stdlibAliases(hasRoutes, hasDB bool) []string {
	var names []string
	if hasDB {
		names = append(names, "sql", "os")
	}
	if hasRoutes {
		names = append(names, "fmt", "http")
	}
	if hasDB || hasRoutes {
		names = append(names, "log")
	}
	return names
}

// validateSlotVarNameUniqueness checks that no two slot bindings produce the
// same derived variable name. Distinct raw composite keys (slot, entity, operator)
// can normalize to the same camelCase identifier when the slot names differ only
// in underscore structure (e.g. "before_create" and "before__create" both produce
// "beforeCreate" via snakeToCamel). This would produce duplicate := declarations
// in the generated main.go.
func validateSlotVarNameUniqueness(bindings []types.SlotDeclaration) error {
	type varSource struct {
		slot, entity, operator string
	}
	seen := make(map[string]varSource) // derived var name → first source

	for _, sb := range bindings {
		operators := []struct {
			name   string
			suffix string
			has    bool
		}{
			{"gate", "Gate", len(sb.Gate) > 0},
			{"chain", "Chain", len(sb.Chain) > 0},
			{"fan-out", "FanOut", len(sb.FanOut) > 0},
		}
		for _, op := range operators {
			if !op.has {
				continue
			}
			varName := slotVarName(sb.Slot, sb.Entity, op.suffix)
			source := varSource{slot: sb.Slot, entity: sb.Entity, operator: op.name}
			if first, ok := seen[varName]; ok {
				// Only report if the raw composite keys differ — if they're
				// identical, validateSlotBindingUniqueness already catches it.
				if first.slot != source.slot || first.entity != source.entity || first.operator != source.operator {
					return fmt.Errorf("slot bindings %q (entity %q, operator %q) and %q (entity %q, operator %q) produce the same variable name %q — slot names must be distinct after normalization",
						first.slot, first.entity, first.operator,
						source.slot, source.entity, source.operator,
						varName)
				}
			}
			seen[varName] = source
		}
	}
	return nil
}

// slotVarName derives a unique slot operator variable name from the slot name,
// entity name (may be empty), and operator type suffix ("Gate", "Chain", "FanOut").
// When an entity is set, the entity name is included to disambiguate per-entity
// bindings of the same slot (e.g. "beforeCreateUserGate" vs "beforeCreateOrgGate").
func slotVarName(slot, entity, operatorSuffix string) string {
	base := snakeToCamel(slot)
	if entity != "" {
		base += entity
	}
	return base + operatorSuffix
}
