package compiler

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/jsell-rh/stego/internal/gen"
	"github.com/jsell-rh/stego/internal/types"
)

func TestAssemble_MinimalService(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewUserHandler(store)"},
					Routes: []string{
						`mux.HandleFunc("POST /users", userHandler.Create)`,
						`mux.HandleFunc("GET /users/{id}", userHandler.Read)`,
					},
				},
			},
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
					NeedsDB:      true,
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	if len(files) != 2 {
		t.Fatalf("expected 2 files (main.go, go.mod), got %d", len(files))
	}

	// Find main.go and go.mod.
	var mainGo, goMod gen.File
	for _, f := range files {
		switch f.Path {
		case "cmd/main.go":
			mainGo = f
		case "go.mod":
			goMod = f
		}
	}

	if mainGo.Path == "" {
		t.Fatal("missing cmd/main.go in output")
	}
	if goMod.Path == "" {
		t.Fatal("missing go.mod in output")
	}

	// Verify main.go has the generated header.
	fullOutput := string(mainGo.Bytes())
	if !strings.HasPrefix(fullOutput, gen.Header) {
		t.Errorf("main.go missing generated header")
	}

	// Verify main.go is valid Go.
	code := string(mainGo.Content)
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse as Go:\n%s\nerror: %v", code, err)
	}

	// Verify it contains expected elements.
	if !strings.Contains(code, "package main") {
		t.Errorf("missing package main")
	}
	if !strings.Contains(code, "http.NewServeMux()") {
		t.Errorf("missing mux creation")
	}
	if !strings.Contains(code, "userHandler.Create") {
		t.Errorf("missing route registration")
	}
	if !strings.Contains(code, "storage.NewStore(db)") {
		t.Errorf("missing store constructor")
	}
	if !strings.Contains(code, "sql.Open") {
		t.Errorf("missing DB setup — NeedsDB is true")
	}

	// Verify go.mod.
	modContent := string(goMod.Content)
	if !strings.Contains(modContent, "module github.com/myorg/svc") {
		t.Errorf("go.mod missing module declaration")
	}
	if !strings.Contains(modContent, "go 1.22") {
		t.Errorf("go.mod missing go version")
	}
	if !strings.Contains(modContent, "Code generated by stego") {
		t.Errorf("go.mod missing generated header comment")
	}
}

func TestAssemble_WithSlotBindings(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewUserHandler(store)"},
					Routes: []string{
						`mux.HandleFunc("POST /users", userHandler.Create)`,
					},
				},
			},
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
					NeedsDB:      true,
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{
				Slot:   "before_create",
				Entity: "User",
				Gate:   []string{"rbac-policy", "admin-creation-policy"},
			},
			{
				Slot:   "on_entity_changed",
				Entity: "User",
				FanOut: []string{"user-change-notifier", "audit-logger"},
			},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	// Verify it parses as Go.
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Verify slot wiring is present.
	if !strings.Contains(code, "slots.NewBeforeCreateGate") {
		t.Errorf("missing gate operator for before_create in:\n%s", code)
	}
	if !strings.Contains(code, "slots.NewOnEntityChangedFanOut") {
		t.Errorf("missing fan-out operator for on_entity_changed in:\n%s", code)
	}

	// Verify fill imports.
	if !strings.Contains(code, "rbacpolicy") {
		t.Errorf("missing rbac-policy fill import in:\n%s", code)
	}
	if !strings.Contains(code, "admincreationpolicy") {
		t.Errorf("missing admin-creation-policy fill import in:\n%s", code)
	}
	if !strings.Contains(code, "userchangenotifier") {
		t.Errorf("missing user-change-notifier fill import in:\n%s", code)
	}
	if !strings.Contains(code, "auditlogger") {
		t.Errorf("missing audit-logger fill import in:\n%s", code)
	}

	// Verify fills are passed to operator constructors.
	if !strings.Contains(code, "rbacpolicy.New()") {
		t.Errorf("missing rbac-policy fill constructor in:\n%s", code)
	}
	if !strings.Contains(code, "admincreationpolicy.New()") {
		t.Errorf("missing admin-creation-policy fill constructor in:\n%s", code)
	}

	// Verify slots package import.
	if !strings.Contains(code, `"github.com/myorg/svc/internal/slots"`) {
		t.Errorf("missing slots package import in:\n%s", code)
	}

	// Verify entity annotation in comments.
	if !strings.Contains(code, "for User") {
		t.Errorf("missing entity annotation in slot wiring comments")
	}

	// Verify operators are wired into handler constructor (not discarded).
	if strings.Contains(code, "_ =") {
		t.Errorf("slot operators should not be discarded with _ = in:\n%s", code)
	}
	// Verify the handler constructor includes slot operator arguments.
	if !strings.Contains(code, "api.NewUserHandler(store, beforeCreateGate, onEntityChangedFanOut)") {
		t.Errorf("slot operators not injected into handler constructor in:\n%s", code)
	}
}

func TestAssemble_ChainWithShortCircuit(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        9090,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler(store)"},
					Routes:       []string{`mux.HandleFunc("POST /items", handler.Create)`},
				},
			},
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
					NeedsDB:      true,
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{
				Slot:         "process_adapter_status",
				Chain:        []string{"validate-conditions", "discard-stale", "persist-status"},
				ShortCircuit: true,
			},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	// Verify it parses.
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Verify chain operator with short-circuit enabled.
	if !strings.Contains(code, "slots.NewProcessAdapterStatusChain(true") {
		t.Errorf("missing chain with short_circuit=true in:\n%s", code)
	}

	// Verify custom port.
	if !strings.Contains(code, "9090") {
		t.Errorf("missing custom port 9090 in:\n%s", code)
	}

	// This slot has no Entity, so the operator can't be injected into a
	// handler constructor and _ = is used to suppress unused variable errors.
	if !strings.Contains(code, "_ = processAdapterStatusChain") {
		t.Errorf("entity-less operator should use _ = to suppress unused var in:\n%s", code)
	}
}

func TestAssemble_WithAuthMiddleware(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "jwt-auth",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/auth"},
					Constructors: []string{"auth.NewAuthMiddleware()"},
				},
			},
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewUserHandler(store)"},
					Routes: []string{
						`mux.HandleFunc("GET /users", userHandler.List)`,
					},
				},
			},
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
					NeedsDB:      true,
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Verify auth middleware wraps the mux.
	if !strings.Contains(code, "authMiddleware.Middleware(mux)") {
		t.Errorf("missing auth middleware wrapping mux in:\n%s", code)
	}
}

func TestAssemble_NoRoutes(t *testing.T) {
	// A service with no routes should still produce valid main.go,
	// and should NOT import "fmt" (which is only used in writeServerStart).
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Wirings: []ComponentWiring{
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
					NeedsDB:      true,
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// No routes means no mux and no server start.
	if strings.Contains(code, "http.NewServeMux") {
		t.Errorf("should not have mux when no routes exist")
	}

	// fmt should not be imported when there are no routes.
	if strings.Contains(code, `"fmt"`) {
		t.Errorf("fmt should not be imported when there are no routes in:\n%s", code)
	}
}

func TestAssemble_FillsDirectoryNeverTouched(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler(store)"},
					Routes:       []string{`mux.HandleFunc("GET /items", handler.List)`},
				},
			},
			{
				Name:   "postgres-adapter",
				Wiring: &gen.Wiring{Imports: []string{"internal/storage"}, Constructors: []string{"storage.NewStore(db)"}, NeedsDB: true},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{Slot: "validate", Gate: []string{"my-fill"}},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	for _, f := range files {
		if strings.HasPrefix(f.Path, "fills/") {
			t.Errorf("assembler generated file under fills/: %s", f.Path)
		}
	}
}

func TestAssemble_EmptyModuleName(t *testing.T) {
	_, err := Assemble(AssemblerInput{GoVersion: "1.22"})
	if err == nil {
		t.Fatal("expected error for empty ModuleName")
	}
}

func TestAssemble_EmptyGoVersion(t *testing.T) {
	_, err := Assemble(AssemblerInput{ModuleName: "mod"})
	if err == nil {
		t.Fatal("expected error for empty GoVersion")
	}
}

func TestAssemble_DefaultPort(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)
	if !strings.Contains(code, "8080") {
		t.Errorf("expected default port 8080 in:\n%s", code)
	}
}

func TestAssemble_NilWiring(t *testing.T) {
	// A component with nil wiring should be skipped gracefully.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{Name: "stub-component", Wiring: nil},
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", string(mainGo.Content), err)
	}
}

func TestAssemble_DeduplicatesFillImports(t *testing.T) {
	// Same fill referenced in two slot bindings should only be imported once.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{Slot: "before_create", Gate: []string{"shared-fill"}},
			{Slot: "validate", Gate: []string{"shared-fill"}},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	// Count occurrences of the fill import — should appear exactly once.
	count := strings.Count(code, `"github.com/myorg/svc/fills/shared-fill"`)
	if count != 1 {
		t.Errorf("fill import should appear once, got %d occurrences in:\n%s", count, code)
	}
}

func TestAssemble_MultipleEntitiesFullWiring(t *testing.T) {
	// Full wiring with multiple entities, slots, and auth middleware.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/user-service",
		ServiceName: "user-management",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
					NeedsDB:      true,
				},
			},
			{
				Name: "jwt-auth",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/auth"},
					Constructors: []string{"auth.NewAuthMiddleware()"},
				},
			},
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports: []string{"internal/api"},
					Constructors: []string{
						"api.NewOrganizationHandler(store)",
						"api.NewUserHandler(store)",
					},
					Routes: []string{
						`mux.HandleFunc("POST /organizations", organizationHandler.Create)`,
						`mux.HandleFunc("GET /organizations/{id}", organizationHandler.Read)`,
						`mux.HandleFunc("POST /users", userHandler.Create)`,
						`mux.HandleFunc("GET /users/{id}", userHandler.Read)`,
						`mux.HandleFunc("PUT /users/{id}", userHandler.Update)`,
						`mux.HandleFunc("GET /users", userHandler.List)`,
					},
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{
				Slot:   "before_create",
				Entity: "User",
				Gate:   []string{"rbac-policy", "admin-creation-policy"},
			},
			{
				Slot:   "on_entity_changed",
				Entity: "User",
				FanOut: []string{"user-change-notifier", "audit-logger"},
			},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Verify all entities' handlers.
	if !strings.Contains(code, "organizationHandler") {
		t.Errorf("missing organizationHandler")
	}
	if !strings.Contains(code, "userHandler") {
		t.Errorf("missing userHandler")
	}

	// Verify auth middleware wraps server.
	if !strings.Contains(code, "authMiddleware.Middleware(mux)") {
		t.Errorf("missing auth middleware in server start")
	}

	// Verify all slots are wired.
	if !strings.Contains(code, "NewBeforeCreateGate") {
		t.Errorf("missing gate operator")
	}
	if !strings.Contains(code, "NewOnEntityChangedFanOut") {
		t.Errorf("missing fan-out operator")
	}

	// Verify slot operators are injected into handler constructor.
	if !strings.Contains(code, "api.NewUserHandler(store, beforeCreateGate, onEntityChangedFanOut)") {
		t.Errorf("slot operators not injected into User handler constructor in:\n%s", code)
	}

	// Organization handler should NOT have slot operators.
	if !strings.Contains(code, "api.NewOrganizationHandler(store)") {
		t.Errorf("Organization handler should have unmodified constructor in:\n%s", code)
	}

	// Verify no discarded operators.
	if strings.Contains(code, "_ =") {
		t.Errorf("slot operators should not be discarded with _ = in:\n%s", code)
	}

	// Verify all routes.
	if !strings.Contains(code, "POST /organizations") {
		t.Errorf("missing POST /organizations route")
	}
	if !strings.Contains(code, "GET /users") {
		t.Errorf("missing GET /users route")
	}
}

func TestConstructorVarName(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"api.NewUserHandler(store)", "userHandler"},
		{"storage.NewStore(db)", "store"},
		{"auth.NewAuthMiddleware()", "authMiddleware"},
		{"api.NewOrganizationHandler(store)", "organizationHandler"},
		{"pkg.New()", "v"},
	}
	for _, tt := range tests {
		got := rawConstructorVarName(tt.input)
		if got != tt.want {
			t.Errorf("rawConstructorVarName(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestFillImportAlias(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"admin-creation-policy", "admincreationpolicy"},
		{"audit-logger", "auditlogger"},
		{"rbac_policy", "rbacpolicy"},
		{"simple", "simple"},
	}
	for _, tt := range tests {
		got := rawFillImportAlias(tt.input)
		if got != tt.want {
			t.Errorf("rawFillImportAlias(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestSnakeToPascal(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"before_create", "BeforeCreate"},
		{"on_entity_changed", "OnEntityChanged"},
		{"validate", "Validate"},
		{"process_adapter_status", "ProcessAdapterStatus"},
	}
	for _, tt := range tests {
		got := snakeToPascal(tt.input)
		if got != tt.want {
			t.Errorf("snakeToPascal(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestDisambiguateAlias(t *testing.T) {
	counts := make(map[string]int)
	used := make(map[string]bool)

	// First use: no suffix.
	got := disambiguateAlias("models", counts, used)
	if got != "models" {
		t.Errorf("first use: got %q, want %q", got, "models")
	}

	// Second use: gets numeric suffix.
	got = disambiguateAlias("models", counts, used)
	if got != "models2" {
		t.Errorf("second use: got %q, want %q", got, "models2")
	}

	// Third use.
	got = disambiguateAlias("models", counts, used)
	if got != "models3" {
		t.Errorf("third use: got %q, want %q", got, "models3")
	}

	// Different base: no suffix.
	got = disambiguateAlias("api", counts, used)
	if got != "api" {
		t.Errorf("different base: got %q, want %q", got, "api")
	}
}

func TestAssemble_ConstructorVarNameCollision(t *testing.T) {
	// Two constructors that derive the same variable name should be
	// disambiguated with numeric suffixes.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "component-a",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/a"},
					Constructors: []string{"a.NewStore(db)"},
					NeedsDB:      true,
				},
			},
			{
				Name: "component-b",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/b"},
					Constructors: []string{"b.NewStore(db)"},
				},
			},
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	// Should parse — disambiguated variable names.
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Verify both store variables exist with distinct names.
	if !strings.Contains(code, "store :=") {
		t.Errorf("missing first store variable in:\n%s", code)
	}
	if !strings.Contains(code, "store2 :=") {
		t.Errorf("missing disambiguated store2 variable in:\n%s", code)
	}
}

func TestAssemble_FillImportAliasCollision(t *testing.T) {
	// Fill names "a-b" and "ab" both produce raw alias "ab".
	// They should be disambiguated.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{Slot: "slot_a", Gate: []string{"a-b"}},
			{Slot: "slot_b", Gate: []string{"ab"}},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	// Should parse — disambiguated aliases.
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Both fill imports should be present with different aliases.
	if !strings.Contains(code, `"github.com/myorg/svc/fills/a-b"`) {
		t.Errorf("missing a-b fill import in:\n%s", code)
	}
	if !strings.Contains(code, `"github.com/myorg/svc/fills/ab"`) {
		t.Errorf("missing ab fill import in:\n%s", code)
	}
}

func TestAssemble_ComponentImportAliasCollision(t *testing.T) {
	// Two components with different import paths sharing the same base
	// (e.g. "internal/api/models" and "internal/storage/models") should get
	// disambiguated aliases.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "component-a",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api/models"},
					Constructors: []string{"models.NewFoo()"},
					Routes:       []string{`mux.HandleFunc("GET /foo", foo.Get)`},
				},
			},
			{
				Name: "component-b",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage/models"},
					Constructors: []string{"models.NewBar()"},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	// Should parse — disambiguated import aliases.
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Both imports should be present.
	if !strings.Contains(code, `"github.com/myorg/svc/internal/api/models"`) {
		t.Errorf("missing api/models import in:\n%s", code)
	}
	if !strings.Contains(code, `"github.com/myorg/svc/internal/storage/models"`) {
		t.Errorf("missing storage/models import in:\n%s", code)
	}

	// Second should have a disambiguated alias.
	if !strings.Contains(code, "models2") {
		t.Errorf("missing disambiguated models2 alias in:\n%s", code)
	}
}

func TestAssemble_NeedsDB_StructuredMetadata(t *testing.T) {
	// NeedsDB should be detected from the structured NeedsDB field,
	// not from constructor expression string matching.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(connection)"},
					NeedsDB:      true,
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)
	if !strings.Contains(code, "sql.Open") {
		t.Errorf("DB setup should be present when NeedsDB is true, regardless of constructor expression:\n%s", code)
	}
}

func TestAssemble_NoDB_WhenNeedsDBFalse(t *testing.T) {
	// Even with "(db)" in constructor string, NeedsDB=false should skip DB setup.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler(db)"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
					NeedsDB:      false,
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)
	if strings.Contains(code, "sql.Open") {
		t.Errorf("DB setup should NOT be present when NeedsDB is false:\n%s", code)
	}
}

func TestExtractEntityFromConstructor(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"api.NewUserHandler(store)", "User"},
		{"api.NewOrganizationHandler(store)", "Organization"},
		{"storage.NewStore(db)", ""},        // Not a handler
		{"auth.NewAuthMiddleware()", ""},     // Not a handler
		{"pkg.NewHandler()", ""},             // Empty entity
		{"api.NewClusterHandler()", "Cluster"},
	}
	for _, tt := range tests {
		got := extractEntityFromConstructor(tt.input)
		if got != tt.want {
			t.Errorf("extractEntityFromConstructor(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestAssemble_UnifiedImportAliasNamespace(t *testing.T) {
	// Finding 7: Component import "internal/storage" produces alias "storage",
	// and a fill named "storage" also produces alias "storage". With separate
	// disambiguation maps these collide; with a unified namespace the fill
	// gets disambiguated to "storage2".
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
					NeedsDB:      true,
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{Slot: "validate", Gate: []string{"storage"}},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	// Must parse as valid Go — separate maps would produce duplicate "storage" alias.
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Both imports should be present with distinct aliases.
	if !strings.Contains(code, `storage "github.com/myorg/svc/internal/storage"`) {
		t.Errorf("missing component storage import in:\n%s", code)
	}
	if !strings.Contains(code, `"github.com/myorg/svc/fills/storage"`) {
		t.Errorf("missing fill storage import in:\n%s", code)
	}
	// The fill alias should be disambiguated.
	if !strings.Contains(code, "storage2") {
		t.Errorf("fill 'storage' alias should be disambiguated to storage2 in:\n%s", code)
	}
}

func TestAssemble_SlotsAliasCollisionWithComponent(t *testing.T) {
	// The hardcoded "slots" alias should be reserved before component
	// imports, so a component with base path "slots" gets disambiguated.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
			{
				Name: "slots-component",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/slots"},
					Constructors: []string{"slots.NewProcessor()"},
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{Slot: "validate", Gate: []string{"my-fill"}},
		},
		SlotsPackage: "pkg/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// The slots package should get the "slots" alias, and the component
	// import should be disambiguated.
	if !strings.Contains(code, "slots2") {
		t.Errorf("component 'internal/slots' alias should be disambiguated when slots package is present in:\n%s", code)
	}
}

func TestAssemble_FillAliasCollisionWithComponent(t *testing.T) {
	// A fill named "api" should not collide with a component import alias "api".
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{Slot: "validate", Gate: []string{"api"}},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// The fill named "api" should get a disambiguated alias since the
	// component already claimed "api".
	if !strings.Contains(code, "api2") {
		t.Errorf("fill 'api' alias should be disambiguated to api2 in:\n%s", code)
	}
}

func TestAssemble_HandlerConstructorCollisionUpdatesRoutes(t *testing.T) {
	// Finding 8: When two handler constructors produce the same base variable
	// name, routes from the second component must reference the disambiguated
	// variable name, not the original.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "component-a",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/a"},
					Constructors: []string{"a.NewUserHandler(store)"},
					Routes: []string{
						`mux.HandleFunc("POST /a/users", userHandler.Create)`,
					},
				},
			},
			{
				Name: "component-b",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/b"},
					Constructors: []string{"b.NewUserHandler(store)"},
					Routes: []string{
						`mux.HandleFunc("POST /b/users", userHandler.Create)`,
					},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// First handler keeps original name.
	if !strings.Contains(code, "userHandler :=") {
		t.Errorf("first handler should keep original variable name in:\n%s", code)
	}
	// Second handler gets disambiguated.
	if !strings.Contains(code, "userHandler2 :=") {
		t.Errorf("second handler should be disambiguated to userHandler2 in:\n%s", code)
	}
	// First route should reference original name.
	if !strings.Contains(code, `userHandler.Create)`) {
		t.Errorf("first route should reference userHandler in:\n%s", code)
	}
	// Second route should reference disambiguated name.
	if !strings.Contains(code, `userHandler2.Create)`) {
		t.Errorf("second route should reference userHandler2 in:\n%s", code)
	}
}

func TestAssemble_NoRoutesNoDB_NoLogImport(t *testing.T) {
	// Finding 9: When neither routes nor DB are present, "log" should not be
	// imported since it is only used in writeDBSetup and writeServerStart.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Wirings: []ComponentWiring{
			{
				Name: "stub",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/stub"},
					Constructors: []string{"stub.NewProcessor()"},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// log should NOT be imported when neither routes nor DB are present.
	if strings.Contains(code, `"log"`) {
		t.Errorf("log should not be imported when no routes and no DB in:\n%s", code)
	}
}

func TestInjectConstructorArgs(t *testing.T) {
	tests := []struct {
		expr string
		args []string
		want string
	}{
		{"api.NewUserHandler(store)", []string{"gateOp"}, "api.NewUserHandler(store, gateOp)"},
		{"api.NewUserHandler(store)", []string{"gateOp", "fanOutOp"}, "api.NewUserHandler(store, gateOp, fanOutOp)"},
		{"api.NewHandler()", []string{"gateOp"}, "api.NewHandler(gateOp)"},
		{"api.NewHandler(store)", nil, "api.NewHandler(store)"},
	}
	for _, tt := range tests {
		got := injectConstructorArgs(tt.expr, tt.args)
		if got != tt.want {
			t.Errorf("injectConstructorArgs(%q, %v) = %q, want %q", tt.expr, tt.args, got, tt.want)
		}
	}
}
