package compiler

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/jsell-rh/stego/internal/gen"
	"github.com/jsell-rh/stego/internal/types"
)

func TestAssemble_MinimalService(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewUserHandler(store)"},
					Routes: []string{
						`mux.HandleFunc("POST /users", userHandler.Create)`,
						`mux.HandleFunc("GET /users/{id}", userHandler.Read)`,
					},
				},
			},
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	if len(files) != 2 {
		t.Fatalf("expected 2 files (main.go, go.mod), got %d", len(files))
	}

	// Find main.go and go.mod.
	var mainGo, goMod gen.File
	for _, f := range files {
		switch f.Path {
		case "cmd/main.go":
			mainGo = f
		case "go.mod":
			goMod = f
		}
	}

	if mainGo.Path == "" {
		t.Fatal("missing cmd/main.go in output")
	}
	if goMod.Path == "" {
		t.Fatal("missing go.mod in output")
	}

	// Verify main.go has the generated header.
	fullOutput := string(mainGo.Bytes())
	if !strings.HasPrefix(fullOutput, gen.Header) {
		t.Errorf("main.go missing generated header")
	}

	// Verify main.go is valid Go.
	code := string(mainGo.Content)
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse as Go:\n%s\nerror: %v", code, err)
	}

	// Verify it contains expected elements.
	if !strings.Contains(code, "package main") {
		t.Errorf("missing package main")
	}
	if !strings.Contains(code, "http.NewServeMux()") {
		t.Errorf("missing mux creation")
	}
	if !strings.Contains(code, "userHandler.Create") {
		t.Errorf("missing route registration")
	}
	if !strings.Contains(code, "storage.NewStore(db)") {
		t.Errorf("missing store constructor")
	}
	if !strings.Contains(code, "sql.Open") {
		t.Errorf("missing DB setup — store constructor uses db param")
	}

	// Verify go.mod.
	modContent := string(goMod.Content)
	if !strings.Contains(modContent, "module github.com/myorg/svc") {
		t.Errorf("go.mod missing module declaration")
	}
	if !strings.Contains(modContent, "go 1.22") {
		t.Errorf("go.mod missing go version")
	}
	if !strings.Contains(modContent, "Code generated by stego") {
		t.Errorf("go.mod missing generated header comment")
	}
}

func TestAssemble_WithSlotBindings(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewUserHandler(store)"},
					Routes: []string{
						`mux.HandleFunc("POST /users", userHandler.Create)`,
					},
				},
			},
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{
				Slot:   "before_create",
				Entity: "User",
				Gate:   []string{"rbac-policy", "admin-creation-policy"},
			},
			{
				Slot:   "on_entity_changed",
				Entity: "User",
				FanOut: []string{"user-change-notifier", "audit-logger"},
			},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	// Verify it parses as Go.
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Verify slot wiring is present.
	if !strings.Contains(code, "slots.NewBeforeCreateGate") {
		t.Errorf("missing gate operator for before_create in:\n%s", code)
	}
	if !strings.Contains(code, "slots.NewOnEntityChangedFanOut") {
		t.Errorf("missing fan-out operator for on_entity_changed in:\n%s", code)
	}

	// Verify fill imports.
	if !strings.Contains(code, "rbacpolicy") {
		t.Errorf("missing rbac-policy fill import in:\n%s", code)
	}
	if !strings.Contains(code, "admincreationpolicy") {
		t.Errorf("missing admin-creation-policy fill import in:\n%s", code)
	}
	if !strings.Contains(code, "userchangenotifier") {
		t.Errorf("missing user-change-notifier fill import in:\n%s", code)
	}
	if !strings.Contains(code, "auditlogger") {
		t.Errorf("missing audit-logger fill import in:\n%s", code)
	}

	// Verify fills are passed to operator constructors.
	if !strings.Contains(code, "rbacpolicy.New()") {
		t.Errorf("missing rbac-policy fill constructor in:\n%s", code)
	}
	if !strings.Contains(code, "admincreationpolicy.New()") {
		t.Errorf("missing admin-creation-policy fill constructor in:\n%s", code)
	}

	// Verify slots package import.
	if !strings.Contains(code, `"github.com/myorg/svc/internal/slots"`) {
		t.Errorf("missing slots package import in:\n%s", code)
	}

	// Verify entity annotation in comments.
	if !strings.Contains(code, "for User") {
		t.Errorf("missing entity annotation in slot wiring comments")
	}
}

func TestAssemble_ChainWithShortCircuit(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        9090,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler(store)"},
					Routes:       []string{`mux.HandleFunc("POST /items", handler.Create)`},
				},
			},
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{
				Slot:         "process_adapter_status",
				Chain:        []string{"validate-conditions", "discard-stale", "persist-status"},
				ShortCircuit: true,
			},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	// Verify it parses.
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Verify chain operator with short-circuit enabled.
	if !strings.Contains(code, "slots.NewProcessAdapterStatusChain(true") {
		t.Errorf("missing chain with short_circuit=true in:\n%s", code)
	}

	// Verify custom port.
	if !strings.Contains(code, "9090") {
		t.Errorf("missing custom port 9090 in:\n%s", code)
	}
}

func TestAssemble_WithAuthMiddleware(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "jwt-auth",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/auth"},
					Constructors: []string{"auth.NewAuthMiddleware()"},
				},
			},
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewUserHandler(store)"},
					Routes: []string{
						`mux.HandleFunc("GET /users", userHandler.List)`,
					},
				},
			},
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Verify auth middleware wraps the mux.
	if !strings.Contains(code, "authMiddleware.Middleware(mux)") {
		t.Errorf("missing auth middleware wrapping mux in:\n%s", code)
	}
}

func TestAssemble_NoRoutes(t *testing.T) {
	// A service with no routes should still produce valid main.go.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Wirings: []ComponentWiring{
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// No routes means no mux and no server start.
	if strings.Contains(code, "http.NewServeMux") {
		t.Errorf("should not have mux when no routes exist")
	}
}

func TestAssemble_FillsDirectoryNeverTouched(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler(store)"},
					Routes:       []string{`mux.HandleFunc("GET /items", handler.List)`},
				},
			},
			{
				Name:   "postgres-adapter",
				Wiring: &gen.Wiring{Imports: []string{"internal/storage"}, Constructors: []string{"storage.NewStore(db)"}},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{Slot: "validate", Gate: []string{"my-fill"}},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	for _, f := range files {
		if strings.HasPrefix(f.Path, "fills/") {
			t.Errorf("assembler generated file under fills/: %s", f.Path)
		}
	}
}

func TestAssemble_EmptyModuleName(t *testing.T) {
	_, err := Assemble(AssemblerInput{GoVersion: "1.22"})
	if err == nil {
		t.Fatal("expected error for empty ModuleName")
	}
}

func TestAssemble_EmptyGoVersion(t *testing.T) {
	_, err := Assemble(AssemblerInput{ModuleName: "mod"})
	if err == nil {
		t.Fatal("expected error for empty GoVersion")
	}
}

func TestAssemble_DefaultPort(t *testing.T) {
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)
	if !strings.Contains(code, "8080") {
		t.Errorf("expected default port 8080 in:\n%s", code)
	}
}

func TestAssemble_NilWiring(t *testing.T) {
	// A component with nil wiring should be skipped gracefully.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{Name: "stub-component", Wiring: nil},
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
		},
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", string(mainGo.Content), err)
	}
}

func TestAssemble_DeduplicatesFillImports(t *testing.T) {
	// Same fill referenced in two slot bindings should only be imported once.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/svc",
		ServiceName: "svc",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/api"},
					Constructors: []string{"api.NewHandler()"},
					Routes:       []string{`mux.HandleFunc("GET /", handler.Index)`},
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{Slot: "before_create", Gate: []string{"shared-fill"}},
			{Slot: "validate", Gate: []string{"shared-fill"}},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	// Count occurrences of the fill import — should appear exactly once.
	count := strings.Count(code, `"github.com/myorg/svc/fills/shared-fill"`)
	if count != 1 {
		t.Errorf("fill import should appear once, got %d occurrences in:\n%s", count, code)
	}
}

func TestAssemble_MultipleEntitiesFullWiring(t *testing.T) {
	// Full wiring with multiple entities, slots, and auth middleware.
	input := AssemblerInput{
		ModuleName:  "github.com/myorg/user-service",
		ServiceName: "user-management",
		GoVersion:   "1.22",
		Port:        8080,
		Wirings: []ComponentWiring{
			{
				Name: "postgres-adapter",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/storage"},
					Constructors: []string{"storage.NewStore(db)"},
				},
			},
			{
				Name: "jwt-auth",
				Wiring: &gen.Wiring{
					Imports:      []string{"internal/auth"},
					Constructors: []string{"auth.NewAuthMiddleware()"},
				},
			},
			{
				Name: "rest-api",
				Wiring: &gen.Wiring{
					Imports: []string{"internal/api"},
					Constructors: []string{
						"api.NewOrganizationHandler(store)",
						"api.NewUserHandler(store)",
					},
					Routes: []string{
						`mux.HandleFunc("POST /organizations", organizationHandler.Create)`,
						`mux.HandleFunc("GET /organizations/{id}", organizationHandler.Read)`,
						`mux.HandleFunc("POST /users", userHandler.Create)`,
						`mux.HandleFunc("GET /users/{id}", userHandler.Read)`,
						`mux.HandleFunc("PUT /users/{id}", userHandler.Update)`,
						`mux.HandleFunc("GET /users", userHandler.List)`,
					},
				},
			},
		},
		SlotBindings: []types.SlotDeclaration{
			{
				Slot:   "before_create",
				Entity: "User",
				Gate:   []string{"rbac-policy", "admin-creation-policy"},
			},
			{
				Slot:   "on_entity_changed",
				Entity: "User",
				FanOut: []string{"user-change-notifier", "audit-logger"},
			},
		},
		SlotsPackage: "internal/slots",
	}

	files, err := Assemble(input)
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}

	var mainGo gen.File
	for _, f := range files {
		if f.Path == "cmd/main.go" {
			mainGo = f
		}
	}

	code := string(mainGo.Content)

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "main.go", mainGo.Content, parser.AllErrors)
	if err != nil {
		t.Fatalf("main.go does not parse:\n%s\nerror: %v", code, err)
	}

	// Verify all entities' handlers.
	if !strings.Contains(code, "organizationHandler") {
		t.Errorf("missing organizationHandler")
	}
	if !strings.Contains(code, "userHandler") {
		t.Errorf("missing userHandler")
	}

	// Verify auth middleware wraps server.
	if !strings.Contains(code, "authMiddleware.Middleware(mux)") {
		t.Errorf("missing auth middleware in server start")
	}

	// Verify all slots are wired.
	if !strings.Contains(code, "NewBeforeCreateGate") {
		t.Errorf("missing gate operator")
	}
	if !strings.Contains(code, "NewOnEntityChangedFanOut") {
		t.Errorf("missing fan-out operator")
	}

	// Verify all routes.
	if !strings.Contains(code, "POST /organizations") {
		t.Errorf("missing POST /organizations route")
	}
	if !strings.Contains(code, "GET /users") {
		t.Errorf("missing GET /users route")
	}
}

func TestConstructorVarName(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"api.NewUserHandler(store)", "userHandler"},
		{"storage.NewStore(db)", "store"},
		{"auth.NewAuthMiddleware()", "authMiddleware"},
		{"api.NewOrganizationHandler(store)", "organizationHandler"},
		{"pkg.New()", "v"},
	}
	for _, tt := range tests {
		got := constructorVarName(tt.input)
		if got != tt.want {
			t.Errorf("constructorVarName(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestFillImportAlias(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"admin-creation-policy", "admincreationpolicy"},
		{"audit-logger", "auditlogger"},
		{"rbac_policy", "rbacpolicy"},
		{"simple", "simple"},
	}
	for _, tt := range tests {
		got := fillImportAlias(tt.input)
		if got != tt.want {
			t.Errorf("fillImportAlias(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestSnakeToPascal(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"before_create", "BeforeCreate"},
		{"on_entity_changed", "OnEntityChanged"},
		{"validate", "Validate"},
		{"process_adapter_status", "ProcessAdapterStatus"},
	}
	for _, tt := range tests {
		got := snakeToPascal(tt.input)
		if got != tt.want {
			t.Errorf("snakeToPascal(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}
