package compiler

import "github.com/jsell-rh/stego/internal/gen"

const httpTLSSource = `

func stegoHTTPTransport() (*tls.Config,error) {
 invalid:=errors.New("invalid HTTP TLS configuration")
 required,present:=os.LookupEnv("STEGO_HTTP_REQUIRE_TLS")
 if present && required!="0" && required!="1" { return nil,invalid }
 certificate,key:=os.Getenv("STEGO_HTTP_TLS_CERT"),os.Getenv("STEGO_HTTP_TLS_KEY")
 if certificate=="" && key=="" && required!="1" { return nil,nil }
 certPEM,err:=stegoHTTPReadTLSFile(certificate,false);if err!=nil{return nil,invalid}
 keyPEM,err:=stegoHTTPReadTLSFile(key,true);if err!=nil{return nil,invalid}
 pair,err:=tls.X509KeyPair(certPEM,keyPEM);if err!=nil{return nil,invalid}
 return &tls.Config{MinVersion:tls.VersionTLS13,Certificates:[]tls.Certificate{pair}},nil
}

func stegoHTTPReadTLSFile(name string,private bool)([]byte,error){
 invalid:=errors.New("invalid HTTP TLS file")
 if len(name)>4096 || !filepath.IsAbs(name){return nil,invalid}
 file,err:=stegoHTTPOpenTLSFile(name);if err!=nil{return nil,invalid};defer file.Close()
 info,err:=file.Stat()
 if err!=nil || !info.Mode().IsRegular() || info.Size()>65536 || private && info.Mode().Perm()&0137!=0{return nil,invalid}
 data,err:=io.ReadAll(io.LimitReader(file,65537));if err!=nil || len(data)>65536{return nil,invalid}
 return data,nil
}
`

func httpTLSFiles() []gen.File {
	return []gen.File{
		{Path: "http_tls_open_unix.go", Content: []byte(`//go:build unix

// Code generated by stego. DO NOT EDIT.
package main
import("os";"syscall")
func stegoHTTPOpenTLSFile(name string)(*os.File,error){return os.OpenFile(name,os.O_RDONLY|syscall.O_NONBLOCK,0)}
`)},
		{Path: "http_tls_open_other.go", Content: []byte(`//go:build !unix

// Code generated by stego. DO NOT EDIT.
package main
import("os";"errors")
func stegoHTTPOpenTLSFile(string)(*os.File,error){return nil,errors.New("HTTP TLS files require a Unix platform")}
`)},
	}
}
