// Code generated by STEGO. DO NOT EDIT.
import type { Tracer, Meter } from '@opentelemetry/api';
import type { Logger } from '@opentelemetry/api-logs';
export interface DeliveryFailure {
 readonly signal: 'traces' | 'logs' | 'metrics';
 readonly reason: 'queue_full' | 'export_failed' | 'invalid_record';
}
export interface Options {
 sampleRatio?: number;
 reportDeliveryFailure?: (failure: Readonly<DeliveryFailure>) => void;
}
export interface BrowserTelemetry {
 readonly tracer: Tracer;
 readonly meter: Meter;
 readonly logger: Logger;
 beginTrace(traceId: string): void;
 forceFlush(): Promise<void>;
 shutdown(): Promise<void>;
}
export function createBrowserTelemetry(options?: Options): BrowserTelemetry;
export class RootTraceIdGenerator {
 primeTraceId(traceId: string): void;
 generateTraceId(): string;
 generateSpanId(): string;
}
