// Package browsertelemetry generates the common browser telemetry runtime.
package browsertelemetry

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"github.com/jsell-rh/stego/internal/gen"
	"path"
	"regexp"
)

type Generator struct{}

//go:embed runtime.js
var runtimeSource string

//go:embed declarations.d.ts
var declarations string

//go:embed package.json
var packageSource []byte
var servicePattern = regexp.MustCompile(`^[a-z][a-z0-9._-]{0,63}$`)

func (*Generator) ValidateContext(ctx gen.Context) error {
	if gen.ValidateGoPackageNamespace(ctx.OutputNamespace) != nil {
		return fmt.Errorf("browser telemetry requires an output namespace")
	}
	if len(ctx.ComponentConfig) != 1 {
		return fmt.Errorf("browser telemetry requires only service_name")
	}
	name, ok := ctx.ComponentConfig["service_name"].(string)
	if !ok || !servicePattern.MatchString(name) {
		return fmt.Errorf("browser telemetry requires a bounded service_name")
	}
	return nil
}
func (g *Generator) Generate(ctx gen.Context) ([]gen.File, *gen.Wiring, error) {
	if err := g.ValidateContext(ctx); err != nil {
		return nil, nil, err
	}
	name, _ := json.Marshal(ctx.ComponentConfig["service_name"])
	files := []gen.File{
		{Path: path.Join(ctx.OutputNamespace, "index.js"), Content: []byte("// Code generated by STEGO. DO NOT EDIT.\nconst serviceName=" + string(name) + ";\n" + runtimeSource)},
		{Path: path.Join(ctx.OutputNamespace, "index.d.ts"), Content: []byte(declarations)},
		{Path: path.Join(ctx.OutputNamespace, "package.json"), Content: packageSource},
	}
	if err := gen.ValidateNamespace(ctx.OutputNamespace, files); err != nil {
		return nil, nil, err
	}
	return files, &gen.Wiring{}, nil
}
