// Package browsertelemetry generates the common browser telemetry runtime.
package browsertelemetry

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"github.com/jsell-rh/stego/internal/gen"
	"github.com/jsell-rh/stego/internal/generator/browseridentity"
	"path"
)

type Generator struct{}

//go:embed runtime.js
var runtimeSource string

//go:embed declarations.d.ts
var declarations string

//go:embed package.json
var packageSource []byte

func (*Generator) ValidateContext(ctx gen.Context) error {
	if gen.ValidateGoPackageNamespace(ctx.OutputNamespace) != nil {
		return fmt.Errorf("browser telemetry requires an output namespace")
	}
	for key := range ctx.ComponentConfig {
		if key != "service_name" {
			return fmt.Errorf("browser telemetry permits only service_name")
		}
	}
	_, err := browseridentity.Resolve(ctx.ServiceName, ctx.ComponentConfig, ctx.PeerConfigs["browser-backend"])
	return err
}
func (g *Generator) Generate(ctx gen.Context) ([]gen.File, *gen.Wiring, error) {
	if err := g.ValidateContext(ctx); err != nil {
		return nil, nil, err
	}
	identity, err := browseridentity.Resolve(ctx.ServiceName, ctx.ComponentConfig, ctx.PeerConfigs["browser-backend"])
	if err != nil {
		return nil, nil, err
	}
	name, _ := json.Marshal(identity)
	files := []gen.File{
		{Path: path.Join(ctx.OutputNamespace, "index.js"), Content: []byte("// Code generated by STEGO. DO NOT EDIT.\nconst serviceName=" + string(name) + ";\n" + runtimeSource)},
		{Path: path.Join(ctx.OutputNamespace, "index.d.ts"), Content: []byte(declarations)},
		{Path: path.Join(ctx.OutputNamespace, "package.json"), Content: packageSource},
	}
	if err := gen.ValidateNamespace(ctx.OutputNamespace, files); err != nil {
		return nil, nil, err
	}
	return files, &gen.Wiring{}, nil
}
