package kubernetesservice

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"path"
	"regexp"
	"sort"
	"strings"

	"github.com/jsell-rh/stego/internal/gen"
)

type worker struct {
	Name, Package, Function string
	Context                 gen.Context
}

var functionName = regexp.MustCompile(`^[A-Z][A-Za-z0-9_]{0,63}$`)

func workers(ctx gen.Context) ([]worker, error) {
	entries, err := configList(ctx, "workers")
	if err != nil {
		return nil, err
	}
	if len(entries) == 0 {
		return nil, nil
	}
	if ctx.PeerNamespaces["controller"] == "" || ctx.ModuleName == "" {
		return nil, fmt.Errorf("workers require the controller component and a module name")
	}
	if err := gen.ValidateGoPackageNamespace(ctx.PeerNamespaces["controller"]); err != nil {
		return nil, err
	}
	dirs, err := sources(ctx)
	if err != nil {
		return nil, err
	}
	allowed := map[string]bool{}
	for _, dir := range dirs {
		if dir != ctx.OutDirName {
			allowed[dir] = true
		}
	}
	seen := map[string]bool{}
	var result []worker
	for _, entry := range entries {
		values, ok := entry.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("worker must be an object")
		}
		name, _ := values["name"].(string)
		pkg, _ := values["package"].(string)
		function, _ := values["function"].(string)
		if !label.MatchString(name) || len(ctx.ServiceName)+len(name)+1 > 50 || seen[name] {
			return nil, fmt.Errorf("worker requires a distinct DNS label and a combined service name of at most 50 bytes")
		}
		seen[name] = true
		segments := strings.Split(pkg, "/")
		if len(pkg) > 256 || len(segments) > 8 || !allowed[segments[0]] || !functionName.MatchString(function) {
			return nil, fmt.Errorf("worker requires an allowed source package and an exported function")
		}
		for _, segment := range segments {
			if !directory.MatchString(segment) {
				return nil, fmt.Errorf("invalid worker package")
			}
		}
		child := ctx
		child.ServiceName = ctx.ServiceName + "-" + name
		child.ComponentConfig = map[string]any{}
		for _, key := range []string{"dns_namespace", "dns_port"} {
			if value, ok := ctx.ComponentConfig[key]; ok {
				child.ComponentConfig[key] = value
			}
		}
		for key, value := range values {
			switch key {
			case "name", "package", "function":
			case "env_secret", "files_secret":
				s, ok := value.(string)
				if !ok || !label.MatchString(s) {
					return nil, fmt.Errorf("worker %s must be a DNS label", key)
				}
				child.ComponentConfig[key] = s
			case "network_peers", "external_endpoints", "kubernetes_api", "kubernetes_permissions":
				child.ComponentConfig[key] = value
			default:
				return nil, fmt.Errorf("unknown worker setting %q", key)
			}
		}
		if _, err := kubernetesAccess(child); err != nil {
			return nil, err
		}
		peers, err := configList(child, "network_peers")
		if err != nil {
			return nil, err
		}
		for _, peer := range peers {
			p, ok := peer.(map[string]any)
			if !ok || p["direction"] != "egress" {
				return nil, fmt.Errorf("workers permit only egress network peers")
			}
		}
		if _, err := networkRules(child); err != nil {
			return nil, err
		}
		declaration := worker{Name: name, Package: pkg, Function: function, Context: child}
		if err := validateWorkerFunction(ctx, declaration); err != nil {
			return nil, err
		}
		result = append(result, declaration)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Name < result[j].Name })
	return result, nil
}

func imageFiles(ctx gen.Context, namespace, target, entrypoint string) []gen.File {
	dirs, _ := sources(ctx)
	var docker, ignore strings.Builder
	docker.WriteString("# Code generated by STEGO. DO NOT EDIT.\nFROM docker.io/library/golang@sha256:2d54f6c8c6ea532a321e0b4c69553b2ed3637608d4f4357dbed37939fe2620cc AS build\nWORKDIR /src\nENV GOTOOLCHAIN=local GOWORK=off CGO_ENABLED=0\nCOPY go.mod go.sum ./\nRUN go mod download\n")
	ignore.WriteString("**\n!go.mod\n!go.sum\n")
	for _, dir := range dirs {
		fmt.Fprintf(&docker, "COPY %s/ ./%s/\n", dir, dir)
		fmt.Fprintf(&ignore, "!%s/\n!%s/**\n", dir, dir)
	}
	ignore.WriteString("**/.*/**\n**/.*\n**/*.key\n**/*.pem\n**/*.p12\n**/*.pfx\n")
	fmt.Fprintf(&docker, "RUN go mod verify && go build -mod=readonly -trimpath -buildvcs=false -o /%s ./%s\nFROM scratch\nCOPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt\nCOPY --from=build --chmod=0555 /%s /%s\nUSER 65532:65532\n", entrypoint, target, entrypoint, entrypoint)
	if entrypoint == "service" {
		docker.WriteString("EXPOSE 8443\n")
	}
	fmt.Fprintf(&docker, "ENTRYPOINT [%q]\n", "/"+entrypoint)
	return []gen.File{{Path: path.Join(namespace, "Containerfile"), Content: []byte(docker.String())}, {Path: path.Join(namespace, "Containerfile.dockerignore"), Content: []byte(ignore.String())}}
}

func workerFiles(ctx gen.Context) ([]gen.File, error) {
	declarations, err := workers(ctx)
	if err != nil {
		return nil, err
	}
	var files []gen.File
	for _, w := range declarations {
		namespace := path.Join(ctx.OutputNamespace, "workers", w.Name)
		files = append(files, imageFiles(ctx, namespace, path.Join(ctx.OutDirName, namespace), "worker")...)
		source := fmt.Sprintf("// Code generated by STEGO. DO NOT EDIT.\npackage main\nimport (application %q; runtime %q)\nfunc main(){runtime.Main(application.%s)}\n", path.Join(ctx.ModuleName, w.Package), path.Join(ctx.ModuleName, ctx.OutDirName, ctx.PeerNamespaces["controller"]), w.Function)
		code, err := format.Source([]byte(source))
		if err != nil {
			return nil, err
		}
		files = append(files, gen.File{Path: path.Join(namespace, "main.go"), Content: code})
		env := []any{object{"name": "GOMEMLIMIT", "value": "384MiB"}, object{"name": "STEGO_DATABASE_ALLOW_INSECURE_LOOPBACK", "value": "0"}, object{"name": "STEGO_CONTROLLER_MONITOR_ADDR", "value": "127.0.0.1:9081"}, object{"name": "OTEL_SERVICE_NAME", "value": w.Context.ServiceName}}
		pod, container := workloadPod(w.Context, env)
		container["name"] = "worker"
		probe := func(mode string, period, threshold int) object {
			return object{"exec": object{"command": []string{"/worker", "--stego-probe=" + mode}}, "timeoutSeconds": 2, "periodSeconds": period, "failureThreshold": threshold}
		}
		container["startupProbe"], container["readinessProbe"], container["livenessProbe"] = probe("live", 2, 30), probe("ready", 3, 2), probe("live", 10, 3)
		metadata := object{"name": w.Context.ServiceName, "namespace": "{{.Namespace}}"}
		labels := object{"app.kubernetes.io/name": w.Context.ServiceName}
		rules, _ := networkRules(w.Context)
		items := []any{
			object{"apiVersion": "v1", "kind": "ServiceAccount", "metadata": metadata, "automountServiceAccountToken": false},
			object{"apiVersion": "networking.k8s.io/v1", "kind": "NetworkPolicy", "metadata": metadata, "spec": rules},
			object{"apiVersion": "apps/v1", "kind": "Deployment", "metadata": metadata, "spec": object{"replicas": 1, "revisionHistoryLimit": 2, "progressDeadlineSeconds": 180, "strategy": object{"type": "Recreate"}, "selector": object{"matchLabels": labels}, "template": object{"metadata": object{"labels": labels}, "spec": pod}}},
		}
		access, _ := kubernetesAccess(w.Context)
		items = append(access, items...)
		manifest, err := json.MarshalIndent(object{"apiVersion": "v1", "kind": "List", "items": items}, "", "  ")
		if err != nil {
			return nil, err
		}
		manifest = bytes.ReplaceAll(manifest, []byte(`"{{.FSGroup}}"`), []byte(`{{.FSGroup}}`))
		files = append(files, gen.File{Path: path.Join(ctx.OutputNamespace, "render", "worker-"+w.Name+".json.tmpl"), Content: manifest})
	}
	return files, nil
}
