// Package browserdom emits DOM helpers for trusted application render output.
package browserdom

import (
	_ "embed"
	"path"

	"github.com/jsell-rh/stego/internal/gen"
)

//go:embed runtime.js
var runtime string

//go:embed declarations.d.ts
var declarations string

// Files is used by the browser backend when dynamic styles are declared.
func Files(namespace string) ([]gen.File, error) {
	files := []gen.File{
		{Path: path.Join(namespace, "index.js"), Content: []byte("// Code generated by STEGO. DO NOT EDIT.\n" + runtime)},
		{Path: path.Join(namespace, "index.d.ts"), Content: []byte(declarations)},
		{Path: path.Join(namespace, "package.json"), Content: []byte("{\"private\":true,\"type\":\"module\",\"main\":\"./index.js\",\"types\":\"./index.d.ts\"}\n")},
	}
	if err := gen.ValidateNamespace(namespace, files); err != nil {
		return nil, err
	}
	return files, nil
}
