// Package typescriptsdk generates browser clients from captured OpenAPI contracts.
package typescriptsdk

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/jsell-rh/stego/internal/gen"
	"github.com/jsell-rh/stego/internal/openapicontract"
)

type Generator struct{}

//go:embed runtime.js
var runtimeSource string

func (*Generator) InputFiles(config map[string]any) ([]string, error) {
	return openapicontract.InputFiles(openAPIConfig(config))
}
func (*Generator) MinimumGoVersion() string { return "1.26.8" }
func (*Generator) ValidateContext(ctx gen.Context) error {
	c, err := compile(ctx)
	if err != nil {
		return err
	}
	_, err = declare(c)
	return err
}
func (*Generator) Generate(ctx gen.Context) ([]gen.File, *gen.Wiring, error) {
	c, err := compile(ctx)
	if err != nil {
		return nil, nil, err
	}
	data, err := json.Marshal(c)
	if err != nil {
		return nil, nil, err
	}
	declarations, err := declare(c)
	if err != nil {
		return nil, nil, err
	}
	js := "// Code generated by STEGO. DO NOT EDIT.\nconst contract = JSON.parse(" + quoted(string(data)) + ");\n" + runtimeSource
	if len(js) > 8<<20 || len(declarations) > 8<<20 {
		return nil, nil, fmt.Errorf("TypeScript SDK output exceeds its limit")
	}
	files := []gen.File{{Path: path.Join(ctx.OutputNamespace, "index.js"), Content: []byte(js)}, {Path: path.Join(ctx.OutputNamespace, "index.d.ts"), Content: []byte(declarations)}, {Path: path.Join(ctx.OutputNamespace, "package.json"), Content: []byte("{\"private\":true,\"type\":\"module\",\"exports\":{\".\":{\"types\":\"./index.d.ts\",\"import\":\"./index.js\"}}}\n")}}
	if err := gen.ValidateNamespace(ctx.OutputNamespace, files); err != nil {
		return nil, nil, err
	}
	return files, &gen.Wiring{}, nil
}

type schema map[string]any
type parameter struct {
	Name     string `json:"name"`
	In       string `json:"in"`
	Required bool   `json:"required"`
	Schema   schema `json:"schema"`
}
type operation struct {
	Method     string            `json:"method"`
	Path       string            `json:"path"`
	Parameters []parameter       `json:"parameters"`
	Body       schema            `json:"body,omitempty"`
	Required   bool              `json:"required"`
	Responses  map[string]schema `json:"responses"`
}
type compiled struct {
	ErrorCodes []string             `json:"errorCodes"`
	Models     map[string]schema    `json:"models"`
	Operations map[string]operation `json:"operations"`
}

func openAPIConfig(config map[string]any) map[string]any {
	result := make(map[string]any, len(config))
	for key, value := range config {
		if key != "error_codes" {
			result[key] = value
		}
	}
	return result
}

var errorCodePattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

func errorCodes(config map[string]any) ([]string, error) {
	codes := []string{}
	if raw, present := config["error_codes"]; present {
		list, ok := raw.([]any)
		if !ok || len(list) > 64 {
			return nil, fmt.Errorf("SDK error_codes requires at most 64 strings")
		}
		seen := map[string]bool{}
		for _, raw := range list {
			code, ok := raw.(string)
			if !ok || len(code) > 128 || !errorCodePattern.MatchString(code) || seen[code] {
				return nil, fmt.Errorf("invalid or duplicate SDK error code")
			}
			seen[code] = true
			codes = append(codes, code)
		}
	}
	sort.Strings(codes)
	return codes, nil
}
func raw(v any) (schema, error) {
	data, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	var s schema
	err = json.Unmarshal(data, &s)
	return s, err
}
func compile(ctx gen.Context) (compiled, error) {
	c := compiled{Models: map[string]schema{}, Operations: map[string]operation{}}
	if gen.ValidateGoPackageNamespace(ctx.OutputNamespace) != nil {
		return c, fmt.Errorf("TypeScript SDK requires an output namespace")
	}
	codes, err := errorCodes(ctx.ComponentConfig)
	if err != nil {
		return c, err
	}
	c.ErrorCodes = codes
	contractContext := ctx
	contractContext.ComponentConfig = openAPIConfig(ctx.ComponentConfig)
	doc, err := openapicontract.Load(contractContext)
	if err != nil {
		return c, err
	}
	if doc.Components != nil {
		for name, ref := range doc.Components.Schemas {
			if ref == nil || ref.Value == nil {
				return c, fmt.Errorf("unresolved SDK model")
			}
			s, err := raw(ref.Value)
			if err != nil {
				return c, err
			}
			c.Models[name] = s
		}
	}
	for route, item := range doc.Paths.Map() {
		if !strings.HasPrefix(route, "/") || strings.HasPrefix(route, "//") || strings.ContainsAny(route, "\\?#\r\n\x00") || path.Clean(route) != route {
			return c, fmt.Errorf("SDK paths must be canonical relative paths")
		}
		for method, op := range item.Operations() {
			if op.OperationID == "login" || op.OperationID == "then" || op.OperationID == "session" || op.OperationID == "logout" {
				return c, fmt.Errorf("reserved TypeScript operation ID")
			}
			if _, ok := c.Operations[op.OperationID]; ok {
				return c, fmt.Errorf("duplicate TypeScript operation ID")
			}
			o := operation{Method: method, Path: route, Parameters: []parameter{}, Responses: map[string]schema{}}
			params := map[string]parameter{}
			combined := append(append(item.Parameters[:0:0], item.Parameters...), op.Parameters...)
			for _, ref := range combined {
				p := ref.Value
				if p == nil || p.Schema == nil || p.Schema.Value == nil {
					return c, fmt.Errorf("SDK parameters require schemas")
				}
				if p.In != "path" && p.In != "query" {
					return c, fmt.Errorf("browser SDK supports path and query parameters")
				}
				if p.AllowReserved || p.AllowEmptyValue || len(p.Content) > 0 || (p.Style != "" && p.Style != "simple" && p.In == "path") || (p.Style != "" && p.Style != "form" && p.In == "query") {
					return c, fmt.Errorf("unsupported SDK parameter encoding")
				}
				s, err := raw(p.Schema.Value)
				if err != nil {
					return c, err
				}
				typ, _ := s["type"].(string)
				if s["nullable"] == true {
					return c, fmt.Errorf("SDK parameters cannot be nullable")
				}
				if typ != "string" && typ != "integer" && typ != "number" && typ != "boolean" {
					return c, fmt.Errorf("SDK parameters must be scalar")
				}
				if p.In == "path" && (!p.Required || !strings.Contains(route, "{"+p.Name+"}")) {
					return c, fmt.Errorf("invalid SDK path parameter")
				}
				params[p.In+":"+p.Name] = parameter{Name: p.Name, In: p.In, Required: p.Required, Schema: s}
			}
			if len(params) > 64 {
				return c, fmt.Errorf("SDK parameter limit exceeded")
			}
			for _, key := range keys(params) {
				o.Parameters = append(o.Parameters, params[key])
			}
			plain := route
			for _, p := range o.Parameters {
				if p.In == "path" {
					plain = strings.ReplaceAll(plain, "{"+p.Name+"}", "value")
				}
			}
			if strings.ContainsAny(plain, "{}") {
				return c, fmt.Errorf("unbound SDK path parameter")
			}
			if op.RequestBody != nil {
				b := op.RequestBody.Value
				if b == nil || b.Content["application/json"] == nil || b.Content["application/json"].Schema == nil {
					return c, fmt.Errorf("SDK body requires a JSON schema")
				}
				o.Body, err = raw(b.Content["application/json"].Schema)
				if err != nil {
					return c, err
				}
				o.Required = b.Required
			}
			for code, ref := range op.Responses.Map() {
				n, err := strconv.Atoi(code)
				if err != nil || n < 200 || n >= 300 {
					continue
				}
				r := ref.Value
				if r == nil {
					return c, fmt.Errorf("unresolved SDK response")
				}
				var s schema
				if len(r.Content) > 0 {
					media := r.Content["application/json"]
					if media == nil || media.Schema == nil {
						return c, fmt.Errorf("SDK response requires a JSON schema")
					}
					s, err = raw(media.Schema)
					if err != nil {
						return c, err
					}
				}
				if method == "HEAD" {
					s = nil
				}
				o.Responses[code] = s
			}
			if len(o.Responses) == 0 {
				return c, fmt.Errorf("SDK operations require explicit success status codes")
			}
			c.Operations[op.OperationID] = o
		}
	}
	for _, s := range c.Models {
		if err := checkSchema(s, c.Models, 0); err != nil {
			return c, err
		}
	}
	for _, o := range c.Operations {
		for _, p := range o.Parameters {
			if err := checkSchema(p.Schema, c.Models, 0); err != nil {
				return c, err
			}
		}
		if err := checkSchema(o.Body, c.Models, 0); err != nil {
			return c, err
		}
		for _, s := range o.Responses {
			if err := checkSchema(s, c.Models, 0); err != nil {
				return c, err
			}
		}
	}
	return c, nil
}
func keys[T any](m map[string]T) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
func child(v any) schema {
	if m, ok := v.(map[string]any); ok {
		return schema(m)
	}
	return nil
}
func refName(s schema) string {
	v, _ := s["$ref"].(string)
	return strings.TrimPrefix(v, "#/components/schemas/")
}
func checkSchema(s schema, models map[string]schema, depth int) error {
	if s == nil {
		return nil
	}
	if depth > 48 {
		return fmt.Errorf("SDK schema depth exceeds limit")
	}
	for key := range s {
		switch key {
		case "$ref", "type", "format", "nullable", "properties", "required", "items", "additionalProperties", "allOf", "oneOf", "anyOf", "enum", "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "minLength", "maxLength", "minItems", "maxItems", "minProperties", "maxProperties", "readOnly", "writeOnly", "description", "title", "default", "example", "deprecated", "externalDocs", "xml", "x-sensitive":
		default:
			return fmt.Errorf("unsupported TypeScript schema keyword %q", key)
		}
	}
	if ref, ok := s["$ref"].(string); ok {
		if !strings.HasPrefix(ref, "#/components/schemas/") || models[refName(s)] == nil {
			return fmt.Errorf("unresolved TypeScript schema reference")
		}
		return nil
	}
	if values, ok := s["enum"].([]any); ok {
		for _, v := range values {
			switch v.(type) {
			case nil, string, float64, bool:
			default:
				return fmt.Errorf("TypeScript enum values must be scalar")
			}
		}
	}
	if typ, ok := s["type"].(string); ok && typ != "object" && typ != "array" && typ != "string" && typ != "integer" && typ != "number" && typ != "boolean" {
		return fmt.Errorf("unsupported TypeScript schema type")
	}
	typ, _ := s["type"].(string)
	for _, rule := range []struct {
		kind  string
		names []string
	}{
		{"object", []string{"properties", "required", "additionalProperties", "minProperties", "maxProperties"}},
		{"array", []string{"items", "minItems", "maxItems"}},
		{"string", []string{"minLength", "maxLength"}},
		{"number", []string{"minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum"}},
	} {
		for _, key := range rule.names {
			if _, present := s[key]; present && typ != rule.kind && !(rule.kind == "number" && typ == "integer") {
				return fmt.Errorf("TypeScript constraint %q requires an explicit matching type", key)
			}
		}
	}
	if format, ok := s["format"].(string); ok {
		switch format {
		case "int32", "int64":
			if typ != "integer" {
				return fmt.Errorf("integer format requires integer type")
			}
		case "float", "double":
			if typ != "number" {
				return fmt.Errorf("number format requires number type")
			}
		case "date-time", "uri", "password":
			if typ != "string" {
				return fmt.Errorf("string format requires string type")
			}
		default:
			return fmt.Errorf("unsupported TypeScript schema format %q", format)
		}
	}
	for _, key := range []string{"allOf", "oneOf", "anyOf"} {
		if values, ok := s[key].([]any); ok {
			for _, v := range values {
				if err := checkSchema(child(v), models, depth+1); err != nil {
					return err
				}
			}
		}
	}
	if props, ok := s["properties"].(map[string]any); ok {
		for _, v := range props {
			if err := checkSchema(child(v), models, depth+1); err != nil {
				return err
			}
		}
	}
	for _, key := range []string{"items", "additionalProperties"} {
		if err := checkSchema(child(s[key]), models, depth+1); err != nil {
			return err
		}
	}
	return nil
}
func quoted(v string) string { data, _ := json.Marshal(v); return string(data) }
func ts(s schema, direction string, models map[string]schema) string {
	if s == nil {
		return "undefined"
	}
	if _, ok := s["$ref"]; ok {
		name := "Schemas"
		if direction == "request" {
			name = "RequestSchemas"
		}
		return name + "[" + quoted(refName(s)) + "]"
	}
	var parts []string
	for _, key := range []string{"allOf", "oneOf", "anyOf"} {
		if list, ok := s[key].([]any); ok {
			var types []string
			for _, v := range list {
				types = append(types, "("+ts(child(v), direction, models)+")")
			}
			sep := " | "
			if key == "allOf" {
				sep = " & "
			}
			parts = append(parts, "("+strings.Join(types, sep)+")")
		}
	}
	typ, _ := s["type"].(string)
	base := "unknown"
	switch typ {
	case "string":
		base = "string"
	case "integer", "number":
		base = "number"
	case "boolean":
		base = "boolean"
	case "array":
		base = "Array<" + ts(child(s["items"]), direction, models) + ">"
	case "object":
		required := map[string]bool{}
		if list, ok := s["required"].([]any); ok {
			for _, v := range list {
				required[v.(string)] = true
			}
		}
		fields := []string{}
		props, _ := s["properties"].(map[string]any)
		for _, name := range keys(props) {
			optional := "?"
			if required[name] {
				optional = ""
			}
			field := child(props[name])
			annotation := field
			for annotation["$ref"] != nil {
				annotation = models[refName(annotation)]
			}
			if (direction == "request" && annotation["readOnly"] == true) || (direction == "response" && annotation["writeOnly"] == true) {
				fields = append(fields, quoted(name)+"?: never;")
				continue
			}
			readonly := ""
			if annotation["readOnly"] == true {
				readonly = "readonly "
			}
			fields = append(fields, readonly+quoted(name)+optional+": "+ts(field, direction, models)+";")
		}
		base = "{ " + strings.Join(fields, " ") + " }"
		if s["additionalProperties"] != false {
			value := "unknown"
			if m := child(s["additionalProperties"]); m != nil {
				value = ts(m, direction, models)
			}
			base += " & { [key: string]: " + value + " }"
		}
	}
	if s["nullable"] == true && typ != "" {
		base = "(" + base + ") | null"
	}
	if values, ok := s["enum"].([]any); ok {
		var enums []string
		for _, v := range values {
			data, _ := json.Marshal(v)
			enums = append(enums, string(data))
		}
		parts = append(parts, "("+strings.Join(enums, " | ")+")")
	}
	if base != "unknown" || len(parts) == 0 {
		parts = append(parts, base)
	}
	for i := range parts {
		parts[i] = "(" + parts[i] + ")"
	}
	return strings.Join(parts, " & ")
}
func declare(c compiled) (string, error) {
	var out strings.Builder
	out.WriteString("// Code generated by STEGO. DO NOT EDIT.\nexport interface RequestSchemas {\n")
	for _, name := range keys(c.Models) {
		fmt.Fprintf(&out, "%s: %s;\n", quoted(name), ts(c.Models[name], "request", c.Models))
	}
	out.WriteString("}\nexport interface Schemas {\n")
	for _, name := range keys(c.Models) {
		fmt.Fprintf(&out, "%s: %s;\n", quoted(name), ts(c.Models[name], "response", c.Models))
	}
	out.WriteString("}\nexport interface RequestOptions { signal?: AbortSignal; traceparent?: string }\nexport interface Result<T> { readonly status: number; readonly body: T; readonly etag: string | null }\nexport interface Session { authenticated: boolean; roles: string[]; user?: { [key: string]: string }; expires_at?: number }\nexport class SDKError extends Error { constructor(code: string, status?: number, apiCode?: string); readonly code: string; readonly status: number; readonly apiCode: string | undefined }\nexport interface Client {\nlogin(): void;\nsession(options?: RequestOptions): Promise<Session>;\nlogout(options?: RequestOptions): Promise<void>;\n")
	for _, name := range keys(c.Operations) {
		o := c.Operations[name]
		fields := []string{}
		required := false
		for _, p := range o.Parameters {
			optional := "?"
			if p.Required {
				optional = ""
				required = true
			}
			fields = append(fields, quoted(p.Name)+optional+": "+ts(p.Schema, "request", c.Models))
		}
		if o.Body != nil {
			optional := "?"
			if o.Required {
				optional = ""
				required = true
			}
			fields = append(fields, "body"+optional+": "+ts(o.Body, "request", c.Models))
		}
		seen := map[string]bool{}
		for _, p := range o.Parameters {
			if seen[p.Name] || p.Name == "body" {
				return "", fmt.Errorf("SDK parameter names conflict")
			}
			seen[p.Name] = true
		}
		optional := "?"
		if required {
			optional = ""
		}
		responses := []string{}
		for _, code := range keys(o.Responses) {
			responses = append(responses, "("+ts(o.Responses[code], "response", c.Models)+")")
		}
		fmt.Fprintf(&out, "%s(input%s: { %s }, options?: RequestOptions): Promise<Result<%s>>;\n", quoted(name), optional, strings.Join(fields, "; "), strings.Join(responses, " | "))
	}
	out.WriteString("}\nexport function createBrowserClient(): Client;\n")
	return out.String(), nil
}
