package typescriptsdk

import (
	"encoding/json"
	"fmt"
	"path"
	"regexp"
	"strings"

	"github.com/jsell-rh/stego/internal/gen"
)

// BrowserSessionFiles uses the SDK transport for an upstream browser API.
// The prefix is fixed by the generated backend. Domain response validation
// remains with that application's client or a generated OpenAPI SDK.
func BrowserSessionFiles(namespace, prefix string) ([]gen.File, error) {
	if gen.ValidateGoPackageNamespace(namespace) != nil || prefix == "/" || !regexp.MustCompile(`^/[A-Za-z0-9_./-]+$`).MatchString(prefix) || len(prefix) > 256 || path.Clean(prefix) != prefix || strings.Contains(prefix, "//") {
		return nil, fmt.Errorf("browser session client requires a namespace and API prefix")
	}
	for _, reserved := range []string{"/auth", "/telemetry", "/assets", "/index.html", "/livez", "/readyz"} {
		if prefix == reserved || strings.HasPrefix(prefix, reserved+"/") {
			return nil, fmt.Errorf("browser session client cannot use a reserved prefix")
		}
	}
	contract, err := json.Marshal(map[string]any{"apiPrefix": prefix, "operations": map[string]any{}, "models": map[string]any{}, "errorCodes": []string{}})
	if err != nil {
		return nil, err
	}
	files := []gen.File{
		{Path: path.Join(namespace, "index.js"), Content: []byte("// Code generated by STEGO. DO NOT EDIT.\nconst contract=" + string(contract) + ";\n" + runtimeSource)},
		{Path: path.Join(namespace, "index.d.ts"), Content: []byte(sessionDeclarations)},
		{Path: path.Join(namespace, "package.json"), Content: []byte("{\"private\":true,\"type\":\"module\",\"exports\":{\".\":{\"types\":\"./index.d.ts\",\"import\":\"./index.js\"}}}\n")},
	}
	return files, gen.ValidateNamespace(namespace, files)
}

const sessionDeclarations = `// Code generated by STEGO. DO NOT EDIT.
export interface RequestOptions { signal?: AbortSignal; traceparent?: string; }
export interface JSONResponse { readonly status: number; readonly body: unknown; readonly etag: string | null; }
export interface Session { readonly authenticated: boolean; readonly roles: readonly string[]; readonly user?: Readonly<Record<string,string>>; readonly expires_at?: number; }
export class SDKError extends Error { readonly code: string; readonly status: number; readonly apiCode?: string; }
export interface BrowserClient {
 request(method: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE', path: string, body?: unknown, options?: RequestOptions): Promise<Readonly<JSONResponse>>;
 session(options?: RequestOptions): Promise<Readonly<Session>>;
 login(): void;
 // Opens the generated sign-out confirmation page.
 logout(): void;
}
export function createBrowserClient(): Readonly<BrowserClient>;
`
